import { ImagenProducto } from "@/components/productos/imagen-producto";
import Link from "next/link";
import { BuscadorModelos } from "@/components/smart-match/buscador-modelos";
import { prisma } from "@/lib/prisma";
import { calcularCompatibilidad, type PantallaComparable } from "@/lib/smart-match/calcular-compatibilidad";
import type { SeccionFtf } from "@/lib/ftf/extraer-url";

export const dynamic = "force-dynamic";

const normalizarClaveFtf = (valor: string) => valor.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
const detalleFtf = (secciones: unknown): Record<string, string> => Object.fromEntries(((secciones as SeccionFtf[] | null) ?? []).flatMap((seccion) => seccion.campos.map((campo, indice) => [`${normalizarClaveFtf(seccion.clave)}:${normalizarClaveFtf(campo.etiqueta)}:${indice}`, campo.valores.join(" | ")] as const)));
const aComparable = (pantalla: { anchoDisplayMm: unknown; altoDisplayMm: unknown; diagonalMm: unknown; tipoFormaPantalla: string; tipoFormaOtro: string | null; aspectRatio: string; areaDisplayPorcentaje: unknown; cristalFrontal: string | null; tecnologia: string | null }, fichaB?: { anchoCuerpoMm: unknown; altoCuerpoMm: unknown; biselLateralMm: unknown; biselVerticalTotalMm: unknown; huellaBajoPantalla: boolean | null } | null, seccionesFtf?: unknown): PantallaComparable => ({
  anchoDisplayMm: Number(pantalla.anchoDisplayMm), altoDisplayMm: Number(pantalla.altoDisplayMm), diagonalMm: Number(pantalla.diagonalMm), tipoFormaPantalla: pantalla.tipoFormaPantalla, tipoFormaOtro: pantalla.tipoFormaOtro, aspectRatio: pantalla.aspectRatio, areaDisplayPorcentaje: pantalla.areaDisplayPorcentaje == null ? null : Number(pantalla.areaDisplayPorcentaje), cristalFrontal: pantalla.cristalFrontal, tecnologia: pantalla.tecnologia,
  anchoCuerpoMm: fichaB?.anchoCuerpoMm == null ? null : Number(fichaB.anchoCuerpoMm), altoCuerpoMm: fichaB?.altoCuerpoMm == null ? null : Number(fichaB.altoCuerpoMm), biselLateralMm: fichaB?.biselLateralMm == null ? null : Number(fichaB.biselLateralMm), biselVerticalTotalMm: fichaB?.biselVerticalTotalMm == null ? null : Number(fichaB.biselVerticalTotalMm), huellaBajoPantalla: fichaB?.huellaBajoPantalla ?? null,
  detalleFtf: detalleFtf(seccionesFtf),
});

export default async function BuscarCristal({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const modelo = typeof params.modelo === "string" ? params.modelo.trim() : "";
  const referencias = modelo ? await prisma.producto.findMany({
    where: { modelo: { contains: modelo, mode: "insensitive" }, tipoProducto: { categoria: "CRISTAL_TEMPLADO" }, especificacionPantalla: { isNot: null } },
    take: 10, include: { especificacionPantalla: true, fichaTecnicaB: true, fichaTecnicaFull: { select: { secciones: true } }, linea: true, marca: true },
  }) : [];
  const referencia = referencias.sort((a, b) => Number(a.modelo.toLocaleLowerCase("es-MX") !== modelo.toLocaleLowerCase("es-MX")) - Number(b.modelo.toLocaleLowerCase("es-MX") !== modelo.toLocaleLowerCase("es-MX")))[0];
  const cristales = referencia ? await prisma.producto.findMany({
    where: { tipoProducto: { categoria: "CRISTAL_TEMPLADO" }, existencia: { gt: 0 }, especificacionPantalla: { isNot: null }, NOT: { modelo: { equals: referencia.modelo, mode: "insensitive" } } },
    include: { especificacionPantalla: true, fichaTecnicaB: true, fichaTecnicaFull: { select: { secciones: true } }, linea: true, marca: true },
  }) : [];
  const resultados = referencia?.especificacionPantalla ? cristales
    .map((cristal) => ({ cristal, resultado: calcularCompatibilidad(aComparable(referencia.especificacionPantalla!, referencia.fichaTecnicaB, referencia.fichaTecnicaFull?.secciones), aComparable(cristal.especificacionPantalla!, cristal.fichaTecnicaB, cristal.fichaTecnicaFull?.secciones)) }))
    .sort((a, b) => b.resultado.porcentaje - a.resultado.porcentaje || a.resultado.diferenciaAnchoMm - b.resultado.diferenciaAnchoMm || a.resultado.diferenciaAltoMm - b.resultado.diferenciaAltoMm || Number(b.resultado.formaCoincide) - Number(a.resultado.formaCoincide) || b.cristal.existencia - a.cristal.existencia)
    .slice(0, 5) : [];

  return <main className="px-4 pb-28 pt-8 sm:px-8 xl:px-12">
    <header className="mb-8"><p className="mb-2 font-mono text-xs uppercase tracking-[0.18em] text-[var(--primary)]">Smart Match</p><h1 className="text-3xl font-bold sm:text-5xl">Buscar cristal compatible</h1><p className="mt-2 max-w-3xl text-[var(--on-surface-variant)]">Introduce un modelo reciente para encontrar los cinco cristales templados en stock con mayor compatibilidad técnica.</p></header>
    <BuscadorModelos inicial={modelo} />
    {modelo && !referencia && <EstadoVacio titulo="No encontramos una ficha de referencia" texto={`Registra el cristal templado de ${modelo} y agrega sus especificaciones; puede tener existencia cero.`} />}
    {referencia?.especificacionPantalla && <section className="mb-7 rounded-[2.5rem] border border-white/60 bg-white/45 p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><Miniatura url={referencia.imagenUrl} descripcion={referencia.descripcion} /><div><span className="font-mono text-xs uppercase text-[var(--primary)]">Producto que estás buscando · Clave {referencia.clave}</span><h2 className="text-2xl font-bold">{referencia.modelo}</h2><p className="text-[var(--on-surface-variant)]">{referencia.marca.nombre} · {referencia.descripcion}</p><div className="mt-3 flex flex-wrap gap-2"><DatoPantalla icono="bx-ruler" texto={`Pantalla de ${Number(referencia.especificacionPantalla.diagonalPulgadas).toFixed(2)} pulgadas`} /><DatoPantalla icono="bx-expand" texto={`Mide ${Number(referencia.especificacionPantalla.anchoDisplayMm).toFixed(2)} mm de ancho y ${Number(referencia.especificacionPantalla.altoDisplayMm).toFixed(2)} mm de alto`} /><DatoPantalla icono="bx-shape-square" texto={`Proporción ${proporcionLegible(referencia.especificacionPantalla.aspectRatio)}`} /></div></div></div></section>}
    {referencia && !resultados.length && <EstadoVacio titulo="No hay cristales comparables" texto="Registra fichas técnicas para cristales templados y asegúrate de que tengan existencia." />}
    {resultados.length > 0 && <section><h2 className="mb-5 text-2xl font-bold">Las 5 mejores opciones</h2><div className="space-y-5">{resultados.map(({ cristal, resultado }, indice) => <article key={cristal.id} className="rounded-[2.5rem] border border-white/60 bg-white/45 p-6 backdrop-blur-xl">
      <div className="grid gap-6 lg:grid-cols-[auto_minmax(0,1fr)_12rem]"><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[var(--primary)] font-bold text-white">{indice + 1}</span><Miniatura url={cristal.imagenUrl} descripcion={cristal.descripcion} /></div><div><p className="font-mono text-xs font-semibold text-[var(--primary)]">Clave {cristal.clave}</p><h3 className="text-xl font-bold">{cristal.descripcion}</h3><p className="text-[var(--on-surface-variant)]">{cristal.marca.nombre} · {cristal.modelo} · {cristal.linea.nombre} · Existencia: {cristal.existencia}</p><p className="mt-3 inline-flex items-center gap-2 rounded-full bg-purple-100 px-4 py-2 font-semibold text-[var(--primary)]"><i className="bx bx-ruler" />Pantalla de {Number(cristal.especificacionPantalla!.diagonalPulgadas).toFixed(2)} pulgadas</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><ComparacionMedida nombre="Ancho de pantalla" buscado={Number(referencia!.especificacionPantalla!.anchoDisplayMm)} opcion={Number(cristal.especificacionPantalla!.anchoDisplayMm)} diferencia={resultado.diferenciaAnchoMm} /><ComparacionMedida nombre="Alto de pantalla" buscado={Number(referencia!.especificacionPantalla!.altoDisplayMm)} opcion={Number(cristal.especificacionPantalla!.altoDisplayMm)} diferencia={resultado.diferenciaAltoMm} /></div></div><div className="text-center lg:text-right"><strong className="block text-4xl text-[var(--primary)]">{resultado.porcentaje}%</strong><span className="mt-2 inline-block rounded-full bg-purple-100 px-3 py-1 text-sm font-semibold text-[var(--primary)]">{resultado.estado}</span><small className="mt-2 block text-[var(--on-surface-variant)]">{resultado.nivel}</small></div></div>
      <p className="mt-4 font-mono text-xs text-[var(--on-surface-variant)]">Cobertura técnica comparada: {resultado.cobertura}%</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Detalle titulo="Coincidencias" icono="bx-check" clase="bg-emerald-50 text-emerald-800" textos={resultado.coincidencias} /><Detalle titulo="Observaciones" icono="bx-error-circle" clase="bg-amber-50 text-amber-900" textos={resultado.advertencias} vacio="Sin diferencias relevantes." /></div><Link href={`/productos/${cristal.id}/editar`} className="mt-5 inline-flex items-center gap-2 rounded-full bg-purple-100 px-5 py-3 font-semibold text-[var(--primary)]">Abrir producto<i className="bx bx-right-arrow-alt" /></Link>
    </article>)}</div></section>}
  </main>;
}

function Miniatura({ url, descripcion }: { url: string | null; descripcion: string }) { return <div className="relative grid size-20 shrink-0 place-items-center overflow-hidden rounded-2xl bg-purple-100 text-3xl text-[var(--primary)]"><ImagenProducto url={url} descripcion={descripcion} sizes="80px" icono="bx-image" /></div>; }
function EstadoVacio({ titulo, texto }: { titulo: string; texto: string }) { return <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-9 text-center"><i className="bx bx-search-alt text-5xl text-[var(--primary)]" /><h2 className="mt-3 text-2xl font-bold">{titulo}</h2><p className="mt-2 text-[var(--on-surface-variant)]">{texto}</p></section>; }
function Detalle({ titulo, icono, clase, textos, vacio }: { titulo: string; icono: string; clase: string; textos: string[]; vacio?: string }) { return <div className={`rounded-2xl p-4 ${clase}`}><h4 className="font-semibold">{titulo}</h4>{textos.length ? <ul className="mt-2 space-y-1 text-sm">{textos.map((texto) => <li key={texto}><i className={`bx ${icono} mr-2`} />{texto}</li>)}</ul> : <p className="mt-2 text-sm">{vacio}</p>}</div>; }
function DatoPantalla({ icono, texto }: { icono: string; texto: string }) { return <span className="inline-flex items-center gap-2 rounded-full bg-purple-100 px-4 py-2 text-sm font-semibold text-[var(--primary)]"><i className={`bx ${icono}`} />{texto}</span>; }
function ComparacionMedida({ nombre, buscado, opcion, diferencia }: { nombre: string; buscado: number; opcion: number; diferencia: number }) { return <div className="rounded-2xl bg-white/60 p-4"><strong className="block">{nombre}</strong><p className="mt-1 text-[var(--on-surface-variant)]">Buscado: <span className="font-mono text-[var(--on-surface)]">{buscado.toFixed(2)} mm</span></p><p className="text-[var(--on-surface-variant)]">Esta opción: <span className="font-mono text-[var(--on-surface)]">{opcion.toFixed(2)} mm</span></p><p className={`mt-2 font-semibold ${diferencia <= 0.01 ? "text-emerald-700" : "text-amber-800"}`}>{diferencia <= 0.01 ? "Misma medida" : `${diferencia.toFixed(2)} mm de diferencia`}</p></div>; }
function proporcionLegible(valor: string) { const partes = valor.split(":").map(Number); if (partes.length === 2 && partes.every(Number.isFinite) && partes[1] > 0) return `${valor} (pantalla ${partes[0] / partes[1] >= 2 ? "alargada" : "estándar"})`; return valor; }
