import Image from "next/image";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { calcularCompatibilidad, type PantallaComparable } from "@/lib/smart-match/calcular-compatibilidad";

export const dynamic = "force-dynamic";
const aComparable = (pantalla: { anchoDisplayMm: unknown; altoDisplayMm: unknown; diagonalMm: unknown; tipoFormaPantalla: string; tipoFormaOtro: string | null; aspectRatio: string; areaDisplayPorcentaje: unknown; cristalFrontal: string | null }): PantallaComparable => ({ anchoDisplayMm: Number(pantalla.anchoDisplayMm), altoDisplayMm: Number(pantalla.altoDisplayMm), diagonalMm: Number(pantalla.diagonalMm), tipoFormaPantalla: pantalla.tipoFormaPantalla, tipoFormaOtro: pantalla.tipoFormaOtro, aspectRatio: pantalla.aspectRatio, areaDisplayPorcentaje: Number(pantalla.areaDisplayPorcentaje), cristalFrontal: pantalla.cristalFrontal });

export default async function BuscarCristal({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const modelo = typeof params.modelo === "string" ? params.modelo.trim() : "";
  const telefonos = modelo ? await prisma.producto.findMany({ where: { modelo: { contains: modelo, mode: "insensitive" }, NOT: { linea: { nombre: { equals: "Cristal templado para celular", mode: "insensitive" } } }, especificacionPantalla: { isNot: null } }, take: 10, include: { especificacionPantalla: true, linea: true, marca: true } }) : [];
  const telefono = telefonos.sort((a, b) => Number(a.modelo.toLocaleLowerCase("es-MX") !== modelo.toLocaleLowerCase("es-MX")) - Number(b.modelo.toLocaleLowerCase("es-MX") !== modelo.toLocaleLowerCase("es-MX")))[0];
  const cristales = telefono ? await prisma.producto.findMany({ where: { linea: { nombre: { equals: "Cristal templado para celular", mode: "insensitive" } }, existencia: { gt: 0 }, especificacionPantalla: { isNot: null } }, include: { especificacionPantalla: true, linea: true, marca: true } }) : [];
  const resultados = telefono?.especificacionPantalla ? cristales.map((cristal) => ({ cristal, resultado: calcularCompatibilidad(aComparable(telefono.especificacionPantalla!), aComparable(cristal.especificacionPantalla!)) })).sort((a, b) => b.resultado.porcentaje - a.resultado.porcentaje || a.resultado.diferenciaAnchoMm - b.resultado.diferenciaAnchoMm || a.resultado.diferenciaAltoMm - b.resultado.diferenciaAltoMm || b.cristal.existencia - a.cristal.existencia).slice(0, 3) : [];

  return <main className="px-4 pb-28 pt-8 sm:px-8 xl:px-12"><header className="mb-8"><p className="mb-2 font-mono text-xs uppercase tracking-[0.18em] text-[var(--primary)]">Smart Match</p><h1 className="text-3xl font-bold sm:text-5xl">Buscar cristal compatible</h1><p className="mt-2 max-w-3xl text-[var(--on-surface-variant)]">Introduce el modelo del teléfono para encontrar los tres cristales templados en stock con mayor compatibilidad técnica.</p></header>
    <form className="mb-8 flex flex-col gap-3 rounded-[2.5rem] border border-white/60 bg-white/40 p-5 backdrop-blur-xl sm:flex-row"><label className="relative flex-1"><span className="sr-only">Modelo del teléfono</span><i className="bx bx-search absolute left-5 top-1/2 -translate-y-1/2 text-xl text-[var(--primary)]" /><input required name="modelo" defaultValue={modelo} placeholder="Ej. Honor 600 Pro" className="w-full rounded-full border border-white/60 bg-white/70 py-4 pl-12 pr-5 outline-none focus:ring-2 focus:ring-purple-400/50" /></label><button className="rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-7 py-4 font-bold text-white">Comparar cristales</button></form>
    {modelo && !telefono && <EstadoVacio titulo="No encontramos la ficha del teléfono" texto={`Registra primero las especificaciones de pantalla de ${modelo}.`} />}
    {telefono && <section className="mb-7 rounded-[2.5rem] border border-white/60 bg-white/45 p-6"><div className="flex items-center gap-4"><Miniatura url={telefono.imagenUrl} descripcion={telefono.descripcion} /><div><span className="font-mono text-xs uppercase text-[var(--primary)]">Teléfono analizado</span><h2 className="text-2xl font-bold">{telefono.modelo}</h2><p className="text-[var(--on-surface-variant)]">{telefono.marca.nombre} · {telefono.descripcion}</p></div></div></section>}
    {telefono && !resultados.length && <EstadoVacio titulo="No hay cristales comparables" texto="Registra características para cristales de la línea Cristal templado para celular y asegúrate de que tengan existencia." />}
    {resultados.length > 0 && <section><h2 className="mb-5 text-2xl font-bold">Las 3 mejores opciones</h2><div className="space-y-5">{resultados.map(({ cristal, resultado }, indice) => <article key={cristal.id} className="rounded-[2.5rem] border border-white/60 bg-white/45 p-6 backdrop-blur-xl"><div className="grid gap-6 lg:grid-cols-[auto_minmax(0,1fr)_10rem]"><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[var(--primary)] font-bold text-white">{indice + 1}</span><Miniatura url={cristal.imagenUrl} descripcion={cristal.descripcion} /></div><div><p className="font-mono text-xs font-semibold text-[var(--primary)]">{cristal.clave}</p><h3 className="text-xl font-bold">{cristal.descripcion}</h3><p className="text-[var(--on-surface-variant)]">{cristal.marca.nombre} · {cristal.modelo} · Existencia: {cristal.existencia}</p><div className="mt-4 grid gap-2 font-mono text-sm sm:grid-cols-2"><span>Ancho: {Number(cristal.especificacionPantalla!.anchoDisplayMm).toFixed(2)} mm (Δ {resultado.diferenciaAnchoMm.toFixed(2)})</span><span>Alto: {Number(cristal.especificacionPantalla!.altoDisplayMm).toFixed(2)} mm (Δ {resultado.diferenciaAltoMm.toFixed(2)})</span></div></div><div className="text-center lg:text-right"><strong className="block text-4xl text-[var(--primary)]">{resultado.porcentaje}%</strong><span className="mt-2 inline-block rounded-full bg-purple-100 px-3 py-1 text-sm font-semibold text-[var(--primary)]">{resultado.estado}</span></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-emerald-50 p-4"><h4 className="font-semibold text-emerald-800">Por qué puede ser compatible</h4><ul className="mt-2 space-y-1 text-sm">{resultado.coincidencias.map((texto) => <li key={texto}><i className="bx bx-check mr-2 text-emerald-700" />{texto}</li>)}</ul></div><div className="rounded-2xl bg-amber-50 p-4"><h4 className="font-semibold text-amber-900">Observaciones</h4>{resultado.advertencias.length ? <ul className="mt-2 space-y-1 text-sm">{resultado.advertencias.map((texto) => <li key={texto}><i className="bx bx-error-circle mr-2 text-amber-700" />{texto}</li>)}</ul> : <p className="mt-2 text-sm">Sin diferencias relevantes.</p>}</div></div><Link href={`/productos/${cristal.id}/editar`} className="mt-5 inline-flex items-center gap-2 rounded-full bg-purple-100 px-5 py-3 font-semibold text-[var(--primary)]">Abrir producto<i className="bx bx-right-arrow-alt" /></Link></article>)}</div></section>}
  </main>;
}

function Miniatura({ url, descripcion }: { url: string | null; descripcion: string }) { return <div className="relative grid size-20 shrink-0 place-items-center overflow-hidden rounded-2xl bg-purple-100 text-3xl text-[var(--primary)]">{url ? <Image unoptimized fill sizes="80px" src={url} alt={`Imagen de ${descripcion}`} className="object-contain" /> : <i className="bx bx-image" />}</div>; }
function EstadoVacio({ titulo, texto }: { titulo: string; texto: string }) { return <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-9 text-center"><i className="bx bx-search-alt text-5xl text-[var(--primary)]" /><h2 className="mt-3 text-2xl font-bold">{titulo}</h2><p className="mt-2 text-[var(--on-surface-variant)]">{texto}</p></section>; }
