import { ImagenProducto } from "@/components/productos/imagen-producto";
import { PaginaCuenta, PaginacionCuenta } from "@/components/mercadolibre/pagina-cuenta";
import { BusquedaEnVivo, FormularioFiltros, GrupoChecks } from "@/components/inventario/filtros-inventario";
import type { Prisma } from "@/generated/prisma/client";
import { obtenerCuentaMercadoLibre, paginaSegura } from "@/lib/mercadolibre/consultas";
import { prisma } from "@/lib/prisma";
export const dynamic = "force-dynamic";

export default async function Publicaciones({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const cuenta = await obtenerCuentaMercadoLibre(); const params = await searchParams; const valor = (clave: string) => typeof params[clave] === "string" ? params[clave] : "";
  const buscar = valor("buscar").trim(), logistica = valor("logistica"), estado = valor("estado"); const paginaSolicitada = paginaSegura(valor("pagina")); const limite = 15;
  if (!cuenta) return <PaginaCuenta cuenta={null} titulo="Publicaciones" descripcion="Publicaciones de la cuenta vendedora."><span /></PaginaCuenta>;
  const where: Prisma.ProductoMercadoLibreWhereInput = { cuentaId: cuenta.id, ...(buscar ? { OR: [{ titulo: { contains: buscar, mode: "insensitive" } }, { publicacionId: { contains: buscar, mode: "insensitive" } }, { codigoVendedor: { contains: buscar, mode: "insensitive" } }, { marca: { contains: buscar, mode: "insensitive" } }] } : {}), ...(logistica ? { logistica } : {}), ...(estado ? { estado: estado === "ACTIVA" ? "active" : { not: "active" } } : {}) };
  const gruposTotales = await prisma.productoMercadoLibre.groupBy({ by: ["publicacionId"], where });
  const total = gruposTotales.length, paginas = Math.max(1, Math.ceil(total / limite)), pagina = Math.min(paginaSolicitada, paginas);
  const grupos = await prisma.productoMercadoLibre.groupBy({ by: ["publicacionId"], where, orderBy: { publicacionId: "asc" }, skip: (pagina - 1) * limite, take: limite, _sum: { existencia: true, vendidos: true }, _count: true });
  const ids = grupos.map(grupo => grupo.publicacionId);
  const filas = await prisma.productoMercadoLibre.findMany({ where: { cuentaId: cuenta.id, publicacionId: { in: ids } }, orderBy: [{ publicacionId: "asc" }, { variacionId: "asc" }] });
  const primeraPorPublicacion = new Map<string, typeof filas[number]>(); filas.forEach(fila => { if (!primeraPorPublicacion.has(fila.publicacionId)) primeraPorPublicacion.set(fila.publicacionId, fila); });
  return <PaginaCuenta cuenta={cuenta} titulo="Publicaciones" descripcion="Publicaciones sincronizadas en modo de solo lectura, presentadas como una galería compacta.">
    <FormularioFiltros className="mb-6 grid gap-3 rounded-[2rem] border border-white/60 bg-white/40 p-4 backdrop-blur-xl sm:grid-cols-3"><label className="relative"><span className="sr-only">Buscar publicaciones</span><i className="bx bx-search absolute left-4 top-1/2 -translate-y-1/2 text-xl text-[var(--outline)]" /><BusquedaEnVivo valor={buscar} placeholder="Buscar nombre, publicación, Código ML o marca…" /></label><GrupoChecks nombre="logistica" etiqueta="Logística" seleccionados={logistica ? [logistica] : []} opciones={[{ valor: "LOCAL", etiqueta: "L · Local" }, { valor: "FULL", etiqueta: "F · Full" }]} /><GrupoChecks nombre="estado" etiqueta="Estado" seleccionados={estado ? [estado] : []} opciones={[{ valor: "ACTIVA", etiqueta: "Activa" }, { valor: "INACTIVA", etiqueta: "Inactiva" }]} /></FormularioFiltros>
    {!grupos.length ? <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-10 text-center"><i className="bx bx-store-alt text-5xl text-[var(--primary)]" /><h2 className="mt-3 text-2xl font-semibold">Sin publicaciones sincronizadas</h2><p className="mt-2 text-[var(--on-surface-variant)]">Actualiza el catálogo desde la sección Productos.</p></section> : <div className="grid items-start gap-4 sm:grid-cols-2 xl:grid-cols-3">{grupos.map(grupo => { const publicacion = primeraPorPublicacion.get(grupo.publicacionId)!; const activa = publicacion.estado === "active"; return <article key={grupo.publicacionId} className="rounded-[2rem] border border-white/60 bg-white/40 p-4 shadow-[0_20px_50px_rgba(0,0,0,0.05)] backdrop-blur-xl"><div className="flex min-w-0 items-start gap-4"><div className="relative grid size-24 shrink-0 place-items-center overflow-hidden rounded-2xl bg-gradient-to-br from-purple-100 to-pink-100 text-3xl text-[var(--primary)]"><ImagenProducto url={publicacion.imagenUrl} descripcion={publicacion.titulo} sizes="96px" icono="bx-store-alt" /></div><div className="min-w-0 flex-1"><p className="font-mono text-xs font-semibold text-[var(--primary)]">{publicacion.publicacionId}</p><h2 className="mt-1 break-words text-base font-semibold leading-snug">{publicacion.titulo}</h2><div className="mt-3 flex flex-wrap gap-2"><span className={`grid size-7 place-items-center rounded-full font-bold text-white ${publicacion.logistica === "FULL" ? "bg-blue-600" : "bg-emerald-600"}`}>{publicacion.logistica === "FULL" ? "F" : "L"}</span><span className={`rounded-full px-3 py-1 text-xs font-semibold ${activa ? "bg-emerald-100 text-emerald-800" : "bg-red-100 text-red-800"}`}>{activa ? "Activa" : "Inactiva"}</span></div></div></div><details className="group mt-4"><summary aria-label={`Mostrar datos de ${publicacion.titulo}`} className="ml-auto grid size-10 cursor-pointer list-none place-items-center rounded-full bg-purple-100 text-xl text-[var(--primary)] group-open:rotate-45"><i className="bx bx-plus" /></summary><dl className="mt-3 grid gap-3 rounded-2xl bg-white/45 p-4 text-sm sm:grid-cols-2"><div><dt className="font-semibold">Variaciones</dt><dd>{grupo._count}</dd></div><div><dt className="font-semibold">Existencia publicada</dt><dd>{grupo._sum.existencia ?? 0}</dd></div><div><dt className="font-semibold">Vendidos</dt><dd>{grupo._sum.vendidos ?? 0}</dd></div><div><dt className="font-semibold">Marca</dt><dd>{publicacion.marca ?? "No informada"}</dd></div><div className="sm:col-span-2"><dt className="font-semibold">Código ML</dt><dd className="font-mono">{publicacion.codigoVendedor ?? "Varía por producto"}</dd></div>{publicacion.enlacePublicacion && <div className="sm:col-span-2"><a href={publicacion.enlacePublicacion} target="_blank" rel="noreferrer" className="font-semibold text-[var(--primary)] hover:underline">Abrir en Mercado Libre <i className="bx bx-link-external" /></a></div>}</dl></details></article>; })}</div>}
    <PaginacionCuenta pagina={pagina} total={total} ruta="/cuenta/publicaciones" limite={limite} query={{ ...(buscar ? { buscar } : {}), ...(logistica ? { logistica } : {}), ...(estado ? { estado } : {}) }} />
  </PaginaCuenta>;
}
