import Link from "next/link";
import { ListadoRegistros } from "@/components/smart-match/listado-registros";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
export default async function RegistrosParalelo({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const buscar = typeof params.buscar === "string" ? params.buscar.trim() : ""; const solicitada = Number(typeof params.pagina === "string" ? params.pagina : "1") || 1; const where = buscar ? { producto: { OR: [{ clave: { contains: buscar, mode: "insensitive" as const } }, { modelo: { contains: buscar, mode: "insensitive" as const } }, { descripcion: { contains: buscar, mode: "insensitive" as const } }] } } : {};
  const total = await prisma.especificacionPantalla.count({ where }); const paginas = Math.max(1, Math.ceil(total / 10)); const pagina = Math.min(Math.max(solicitada, 1), paginas);
  const datos = await prisma.especificacionPantalla.findMany({ where, take: 10, skip: (pagina - 1) * 10, orderBy: { actualizadoEn: "desc" }, select: { id: true, producto: { select: { clave: true, descripcion: true, imagenUrl: true } } } });
  const registros = datos.map(d => ({ id: d.id, ...d.producto })); const href = (n: number) => `/paralelo/registros?${new URLSearchParams({ ...(buscar ? { buscar } : {}), pagina: String(n) })}`;
  return <main className="px-4 pb-28 pt-8 sm:px-8 xl:px-12"><header className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 font-mono text-xs uppercase tracking-[0.18em] text-[var(--primary)]">Smart Match</p><h1 className="text-3xl font-bold sm:text-5xl">Registros del paralelo visual</h1><p className="mt-2 text-[var(--on-surface-variant)]">Administra las fichas técnicas utilizadas en las comparaciones.</p></div><Link href="/paralelo/nuevo" className="inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-3 font-semibold text-white"><i className="bx bx-plus" />Nuevo registro técnico</Link></header><form className="mb-6 flex gap-3 rounded-[2rem] border border-white/60 bg-white/40 p-4"><input name="buscar" defaultValue={buscar} placeholder="Buscar por clave, modelo o descripción..." className="min-w-0 flex-1 rounded-full bg-white/60 px-5 py-3 outline-none" /><button className="rounded-full bg-[var(--primary)] px-6 py-3 font-semibold text-white">Buscar</button></form><ListadoRegistros registros={registros} />{paginas > 1 && <nav aria-label="Paginación" className="mt-7 flex justify-center gap-2">{Array.from({ length: paginas }, (_, i) => i + 1).map(n => <Link key={n} href={href(n)} className={`grid size-10 place-items-center rounded-full ${n === pagina ? "bg-[var(--primary)] text-white" : "bg-white/60"}`}>{n}</Link>)}</nav>}</main>;
}
