import Link from "next/link";

const modulos = [{ href: "/configuracion/respaldos", icono: "bx-archive", titulo: "Respaldos", descripcion: "Copias manuales, restauración selectiva, programaciones, retención e historial.", estado: "Disponible" }, { href: "/configuracion/mercadolibre", icono: "bx-store", titulo: "Mercado Libre", descripcion: "Conexión segura de la cuenta vendedora y estado de autorización.", estado: "Disponible" }] as const;

export default function Configuracion() {
  return <main className="px-4 pb-28 pt-8 sm:px-8 lg:pb-10 xl:px-12">
    <header className="mb-8"><p className="font-mono text-xs uppercase tracking-[0.18em] text-[var(--primary)]">Administración del sistema</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-5xl">Configuración</h1><p className="mt-3 max-w-3xl text-[var(--on-surface-variant)]">Administra cada módulo desde un solo lugar. El panel crecerá conforme se habiliten nuevas funciones del sistema.</p></header>
    <section aria-labelledby="titulo-modulos" className="rounded-[2.5rem] border border-white/60 bg-white/40 p-5 shadow-[0_20px_50px_rgba(0,0,0,0.05)] backdrop-blur-xl sm:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--primary)]">Módulos disponibles</p><h2 id="titulo-modulos" className="mt-1 text-2xl font-semibold">Preferencias y herramientas</h2></div><span className="rounded-full bg-purple-100 px-4 py-2 text-sm font-semibold text-[var(--primary)]">{modulos.length} módulo activo</span></div>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{modulos.map(modulo => <Link key={modulo.href} href={modulo.href} className="group rounded-[2rem] border border-white/70 bg-white/50 p-5 hover:bg-white/75 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-400/60"><div className="flex items-start justify-between gap-3"><span className="grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-[var(--primary)] to-[var(--primary-container)] text-2xl text-white shadow-lg"><i className={`bx ${modulo.icono}`} /></span><span className="rounded-full bg-purple-100 px-3 py-1 text-xs font-semibold text-[var(--primary)]">{modulo.estado}</span></div><h3 className="mt-5 text-xl font-semibold">{modulo.titulo}</h3><p className="mt-2 text-sm leading-relaxed text-[var(--on-surface-variant)]">{modulo.descripcion}</p><span className="mt-5 inline-flex items-center gap-2 font-semibold text-[var(--primary)]">Abrir configuración <i className="bx bx-right-arrow-alt text-xl transition-transform group-hover:translate-x-1" /></span></Link>)}</div>
    </section>
    <aside className="mt-6 rounded-[2rem] border border-white/60 bg-white/35 p-5 text-sm text-[var(--on-surface-variant)] backdrop-blur-xl"><div className="flex gap-3"><i className="bx bx-info-circle mt-0.5 text-xl text-[var(--primary)]" /><div><h2 className="font-semibold text-[var(--on-surface)]">Panel preparado para crecer</h2><p className="mt-1">Cada módulo futuro tendrá aquí su acceso y conservará sus propias validaciones, permisos y estado persistente.</p></div></div></aside>
  </main>;
}
