import { prisma } from "@/lib/prisma";
import { GestorConexionMercadoLibre } from "@/components/mercadolibre/gestor-conexion";
export const dynamic = "force-dynamic";

export default async function ConfiguracionMercadoLibre({ searchParams }: { searchParams: Promise<{ conexion?: string }> }) {
  const [cuenta, parametros] = await Promise.all([prisma.cuentaMercadoLibre.findFirst({ orderBy: { actualizadoEn: "desc" } }), searchParams]);
  const aviso = parametros.conexion === "correcta" ? "La cuenta quedó conectada correctamente." : parametros.conexion === "cancelada" ? "La autorización fue cancelada." : parametros.conexion === "error" ? "No fue posible completar la autorización. Intenta conectarla nuevamente." : null;
  return <main className="px-4 pb-28 pt-8 sm:px-8 lg:pb-10 xl:px-12"><header className="mb-8"><p className="font-mono text-xs uppercase tracking-[0.18em] text-[var(--primary)]">Configuración</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-5xl">Mercado Libre</h1><p className="mt-2 max-w-3xl text-[var(--on-surface-variant)]">Conecta la cuenta vendedora de forma segura. Esta etapa prepara la autenticación; todavía no modifica existencias ni descarga ventas.</p></header>{aviso && <div role="status" className="mb-5 rounded-[1.5rem] border border-white/70 bg-white/55 px-5 py-4 font-semibold text-[var(--primary)]">{aviso}</div>}<section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-6 shadow-[0_20px_50px_rgba(0,0,0,0.05)] backdrop-blur-xl sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--primary)]">Cuenta vendedora</p><h2 className="mt-2 text-2xl font-semibold">{cuenta ? cuenta.apodo ?? `Usuario ${cuenta.usuarioMercadoLibreId}` : "Sin conectar"}</h2>{cuenta && <div className="mt-3 space-y-1 text-sm text-[var(--on-surface-variant)]"><p>ID: {cuenta.usuarioMercadoLibreId}</p><p>Sitio: {cuenta.sitioId ?? "No informado"}</p><p>Autorización vigente hasta: {cuenta.tokenExpiraEn.toLocaleString("es-MX", { timeZone: "America/Mexico_City" })}</p></div>}</div><span className={`rounded-full px-4 py-2 text-sm font-semibold ${cuenta?.ultimoError ? "bg-red-100 text-[var(--error)]" : cuenta ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{cuenta?.ultimoError ? "Requiere reconexión" : cuenta ? "Conectada" : "Pendiente"}</span></div>{cuenta?.ultimoError && <p className="mt-4 rounded-2xl bg-red-50 p-4 text-sm text-[var(--error)]">{cuenta.ultimoError}</p>}<GestorConexionMercadoLibre cuentaId={cuenta?.id} /></section><aside className="mt-6 rounded-[2rem] border border-white/60 bg-white/35 p-5 text-sm text-[var(--on-surface-variant)]"><div className="flex gap-3"><i className="bx bx-shield-quarter text-xl text-[var(--primary)]" /><p>Los tokens se almacenan cifrados y nunca se muestran en esta pantalla. La clave solicitada es la clave administrativa configurada para respaldos.</p></div></aside></main>;
}
