"use client";

import { useState } from "react";
import { cambiarEstadoProgramacion, ejecutarProgramacionAhora, eliminarProgramacion, guardarProgramacion, type DatosProgramacion } from "@/actions/respaldos-programados";

type Catalogo = { clave: string; nombre: string };
type Programacion = DatosProgramacion & { id: string; ultimaEjecucion: string | null; creadoEn: string; actualizadoEn: string };
type Ejecucion = { id: string; programacionId: string; programacion: string; estado: "EN_PROCESO" | "COMPLETADO" | "ERROR"; archivoNombre: string | null; tamanoBytes: number | null; error: string | null; iniciadaEn: string; finalizadaEn: string | null };
const dias = ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"];
const inicial: DatosProgramacion = { nombre: "", activa: true, frecuencia: "SEMANAL", diaSemana: 0, hora: 2, minuto: 0, zonaHoraria: "America/Mexico_City", marcas: [], lineas: [], fichas: "todos", incluirImagenes: true, retencionCantidad: 8 };
const fecha = (valor: string | null) => valor ? new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "medium", timeZone: "America/Mexico_City" }).format(new Date(valor)) : "Nunca";
const tamano = (bytes: number | null) => bytes === null ? "—" : `${(bytes / 1024 / 1024).toLocaleString("es-MX", { maximumFractionDigits: 2 })} MB`;

function Multi({ etiqueta, opciones, valor, cambiar }: { etiqueta: string; opciones: Catalogo[]; valor: string[]; cambiar: (v: string[]) => void }) {
  return <label className="grid gap-2 text-sm font-semibold"><span>{etiqueta}</span><select multiple value={valor} onChange={e => cambiar(Array.from(e.currentTarget.selectedOptions, o => o.value))} className="min-h-32 rounded-2xl border border-white/60 bg-white/70 p-3 font-normal">{opciones.map(o => <option key={o.clave} value={o.clave}>{o.nombre}</option>)}</select><small className="font-normal text-[var(--on-surface-variant)]">Vacío incluye todas. Usa Ctrl o ⌘ para seleccionar varias.</small></label>;
}

export function GestorProgramaciones({ programaciones, ejecuciones, marcas, lineas }: { programaciones: Programacion[]; ejecuciones: Ejecucion[]; marcas: Catalogo[]; lineas: Catalogo[] }) {
  const [clave, setClave] = useState(""), [form, setForm] = useState<DatosProgramacion>(inicial), [editando, setEditando] = useState<string>(), [ocupado, setOcupado] = useState(""), [error, setError] = useState(""), [mensaje, setMensaje] = useState("");
  const ejecutar = async (id: string, accion: () => Promise<unknown>, exito: string) => { setOcupado(id); setError(""); setMensaje(""); try { await accion(); setMensaje(exito); } catch (c) { setError(c instanceof Error ? c.message : "No fue posible completar la operación."); } finally { setOcupado(""); } };
  const editar = (p: Programacion) => { setEditando(p.id); setForm({ nombre: p.nombre, activa: p.activa, frecuencia: p.frecuencia, diaSemana: p.diaSemana, hora: p.hora, minuto: p.minuto, zonaHoraria: p.zonaHoraria, marcas: p.marcas, lineas: p.lineas, fichas: p.fichas, incluirImagenes: p.incluirImagenes, retencionCantidad: p.retencionCantidad }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const guardar = () => ejecutar("guardar", async () => { await guardarProgramacion(clave, form, editando); setForm(inicial); setEditando(undefined); }, editando ? "Programación actualizada." : "Programación creada.");
  return <div className="grid gap-7">
    <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-5 shadow-[0_20px_50px_rgba(0,0,0,0.05)] backdrop-blur-xl sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-semibold">{editando ? "Editar programación" : "Nueva programación"}</h2><p className="mt-1 text-sm text-[var(--on-surface-variant)]">Los nombres incluyen fecha y hora completa: año, mes, día, hora, minuto, segundo y milisegundos.</p></div>{editando && <button onClick={() => { setEditando(undefined); setForm(inicial); }} className="rounded-full bg-white/70 px-4 py-2 font-semibold">Cancelar edición</button>}</div>
      <label className="mt-6 grid gap-2 text-sm font-semibold"><span>Clave administrativa</span><input type="password" value={clave} onChange={e => setClave(e.target.value)} className="rounded-full border border-white/60 bg-white/70 px-5 py-3" /></label>
      <div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><label className="grid gap-2 text-sm font-semibold xl:col-span-2">Nombre<input value={form.nombre} onChange={e => setForm(f => ({ ...f, nombre: e.target.value }))} className="rounded-full bg-white/70 px-5 py-3 font-normal" placeholder="Ej. Respaldo semanal completo" /></label><label className="grid gap-2 text-sm font-semibold">Frecuencia<select value={form.frecuencia} onChange={e => setForm(f => ({ ...f, frecuencia: e.target.value as DatosProgramacion["frecuencia"], diaSemana: e.target.value === "DIARIO" ? null : (f.diaSemana ?? 0) }))} className="rounded-full bg-white/70 px-4 py-3 font-normal"><option value="DIARIO">Diario</option><option value="SEMANAL">Semanal</option></select></label><label className="grid gap-2 text-sm font-semibold">Día<select disabled={form.frecuencia === "DIARIO"} value={form.diaSemana ?? ""} onChange={e => setForm(f => ({ ...f, diaSemana: Number(e.target.value) }))} className="rounded-full bg-white/70 px-4 py-3 font-normal disabled:opacity-50">{dias.map((d,i) => <option key={d} value={i}>{d}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Hora<input type="number" min="0" max="23" value={form.hora} onChange={e => setForm(f => ({ ...f, hora: Number(e.target.value) }))} className="rounded-full bg-white/70 px-4 py-3 font-normal" /></label><label className="grid gap-2 text-sm font-semibold">Minuto<input type="number" min="0" max="59" value={form.minuto} onChange={e => setForm(f => ({ ...f, minuto: Number(e.target.value) }))} className="rounded-full bg-white/70 px-4 py-3 font-normal" /></label><label className="grid gap-2 text-sm font-semibold">Productos<select value={form.fichas} onChange={e => setForm(f => ({ ...f, fichas: e.target.value as DatosProgramacion["fichas"] }))} className="rounded-full bg-white/70 px-4 py-3 font-normal"><option value="todos">Todos, con o sin ficha</option><option value="con">Sólo con ficha técnica</option><option value="sin">Sólo sin ficha técnica</option></select></label><label className="grid gap-2 text-sm font-semibold">Copias a conservar<input type="number" min="1" max="365" value={form.retencionCantidad} onChange={e => setForm(f => ({ ...f, retencionCantidad: Number(e.target.value) }))} className="rounded-full bg-white/70 px-4 py-3 font-normal" /></label><Multi etiqueta="Marcas" opciones={marcas} valor={form.marcas} cambiar={v => setForm(f => ({ ...f, marcas: v }))} /><Multi etiqueta="Líneas" opciones={lineas} valor={form.lineas} cambiar={v => setForm(f => ({ ...f, lineas: v }))} /></div>
      <div className="mt-5 flex flex-wrap gap-4"><label className="flex items-center gap-3 rounded-2xl bg-white/55 p-4 font-semibold"><input type="checkbox" checked={form.incluirImagenes} onChange={e => setForm(f => ({ ...f, incluirImagenes: e.target.checked }))} className="size-5 accent-[var(--primary)]" />Incluir imágenes</label><label className="flex items-center gap-3 rounded-2xl bg-white/55 p-4 font-semibold"><input type="checkbox" checked={form.activa} onChange={e => setForm(f => ({ ...f, activa: e.target.checked }))} className="size-5 accent-[var(--primary)]" />Programación activa</label></div>
      <button disabled={!clave || !form.nombre.trim() || ocupado === "guardar"} onClick={guardar} className="mt-6 w-full rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-3 font-semibold text-white disabled:opacity-50">{ocupado === "guardar" ? "Guardando..." : editando ? "Guardar cambios" : "Crear programación"}</button>{error && <p role="alert" className="mt-4 rounded-2xl bg-red-100 p-4 text-[var(--error)]">{error}</p>}{mensaje && <p role="status" className="mt-4 rounded-2xl bg-purple-100 p-4 text-[var(--primary)]">{mensaje}</p>}
    </section>
    <section><h2 className="mb-4 text-2xl font-semibold">Programaciones</h2>{!programaciones.length ? <div className="rounded-[2rem] bg-white/40 p-8 text-center text-[var(--on-surface-variant)]">Aún no hay respaldos programados.</div> : <div className="grid gap-4 lg:grid-cols-2">{programaciones.map(p => <article key={p.id} className="rounded-[2rem] border border-white/60 bg-white/40 p-5 backdrop-blur-xl"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">{p.nombre}</h3><p className="mt-1 text-sm text-[var(--on-surface-variant)]">{p.frecuencia === "DIARIO" ? "Todos los días" : dias[p.diaSemana ?? 0]} a las {String(p.hora).padStart(2,"0")}:{String(p.minuto).padStart(2,"0")} · {p.zonaHoraria}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${p.activa ? "bg-purple-100 text-[var(--primary)]" : "bg-slate-200 text-slate-600"}`}>{p.activa ? "Activa" : "Pausada"}</span></div><p className="mt-3 text-sm">Última ejecución: <strong>{fecha(p.ultimaEjecucion)}</strong></p><p className="mt-1 text-sm">Conserva {p.retencionCantidad} copia{p.retencionCantidad === 1 ? "" : "s"} · {p.incluirImagenes ? "Con imágenes" : "Sin imágenes"}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => editar(p)} className="rounded-full bg-white/70 px-4 py-2 text-sm font-semibold"><i className="bx bx-edit mr-1" />Editar</button><button disabled={!clave || ocupado === p.id} onClick={() => ejecutar(p.id, () => ejecutarProgramacionAhora(clave,p.id), "Respaldo generado ahora.")} className="rounded-full bg-purple-100 px-4 py-2 text-sm font-semibold text-[var(--primary)]"><i className="bx bx-play mr-1" />Ejecutar ahora</button><button disabled={!clave || ocupado === p.id} onClick={() => ejecutar(p.id, () => cambiarEstadoProgramacion(clave,p.id,!p.activa), p.activa ? "Programación pausada." : "Programación activada.")} className="rounded-full bg-white/70 px-4 py-2 text-sm font-semibold">{p.activa ? "Pausar" : "Activar"}</button><button disabled={!clave || ocupado === p.id} onClick={() => confirm(`¿Eliminar ${p.nombre} y su historial?`) && ejecutar(p.id, () => eliminarProgramacion(clave,p.id), "Programación eliminada.")} className="rounded-full bg-red-100 px-4 py-2 text-sm font-semibold text-[var(--error)]">Eliminar</button></div></article>)}</div>}</section>
    <section><h2 className="mb-4 text-2xl font-semibold">Historial reciente</h2><div className="overflow-x-auto rounded-[2rem] border border-white/60 bg-white/40"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-white/45 font-mono text-xs uppercase text-[var(--on-surface-variant)]"><tr><th className="p-4">Programación</th><th className="p-4">Inicio</th><th className="p-4">Estado</th><th className="p-4">Archivo</th><th className="p-4">Tamaño</th><th className="p-4">Detalle</th></tr></thead><tbody>{ejecuciones.map(e => <tr key={e.id} className="border-t border-white/50"><td className="p-4 font-semibold">{e.programacion}</td><td className="p-4">{fecha(e.iniciadaEn)}</td><td className="p-4"><span className={`rounded-full px-3 py-1 font-semibold ${e.estado === "COMPLETADO" ? "bg-emerald-100 text-emerald-800" : e.estado === "ERROR" ? "bg-red-100 text-[var(--error)]" : "bg-amber-100 text-amber-800"}`}>{e.estado === "COMPLETADO" ? "Completado" : e.estado === "ERROR" ? "Error" : "En proceso"}</span></td><td className="max-w-64 break-all p-4 font-mono text-xs">{e.archivoNombre || "—"}</td><td className="p-4">{tamano(e.tamanoBytes)}</td><td className="max-w-72 p-4 text-[var(--on-surface-variant)]">{e.error || "Respaldo verificado y almacenado."}</td></tr>)}{!ejecuciones.length && <tr><td colSpan={6} className="p-8 text-center text-[var(--on-surface-variant)]">Aún no hay ejecuciones.</td></tr>}</tbody></table></div></section>
  </div>;
}
