"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { ImagenProducto } from "@/components/productos/imagen-producto";
import { useEffect, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { z } from "zod";
import { analizarFichaTecnicaDesdeImagen } from "@/actions/analisis-fichas";
import { analizarFichaBDesdeImagenes, guardarFichaBDesdeImagenes } from "@/actions/fichas-b";
import type { DatosFichaB } from "@/lib/openai/analizar-ficha-b";
import { crearFormaPantallaPersonalizada, guardarEspecificacion } from "@/actions/especificaciones";
import { obtenerRutaRetornoEdicion } from "@/components/layout/persistencia-navegacion";

export interface ProductoTecnico { id: string; clave: string; descripcion: string; modelo: string; imagenUrl: string | null; linea: string; marca: string; tipo: string; fichaA?: Partial<Formulario> | null; fichaB?: DatosFichaB | null; }
const esquema = z.object({ productoId: z.string().min(1, "Selecciona un producto"), tecnologia: z.string().trim().min(1, "Escribe la tecnología"), tipoFormaPantalla: z.string().min(1, "Selecciona una forma"), tipoFormaOtro: z.string(), diagonalMm: z.number().positive("Debe ser mayor que cero"), diagonalPulgadas: z.number().positive("Debe ser mayor que cero"), anchoDisplayMm: z.number().positive("Debe ser mayor que cero"), altoDisplayMm: z.number().positive("Debe ser mayor que cero"), aspectRatio: z.string().trim().min(1, "Escribe el aspect ratio"), resolucionAnchoPx: z.number().int().positive("Resolución inválida"), resolucionAltoPx: z.number().int().positive("Resolución inválida"), densidadPpi: z.number().int().positive("Densidad inválida"), profundidadColor: z.string().trim().min(1, "Escribe la profundidad de color"), areaDisplayPorcentaje: z.number().min(0).max(100, "El área debe estar entre 0 y 100"), cristalFrontal: z.string(), refrescoHz: z.number().int().positive("Frecuencia inválida").nullable() }).refine(d => d.tipoFormaPantalla !== "OTRO" || d.tipoFormaOtro.trim(), { path: ["tipoFormaOtro"], message: "Describe la forma" });
type Formulario = z.infer<typeof esquema>;
const formas = [["PLANA", "Pantallas planas (Cristal 2D)"], ["DOS_PUNTO_CINCO_D", "Cristal 2.5D (Pantalla plana con borde biselado)"], ["CURVA", "Pantallas curvas (3D o Dual-Edge)"], ["TRES_D", "Evoluciones extremas: Waterfall y 4D (Quad-Curved)"], ["PLEGABLE", "Pantallas plegables (Foldables)"], ["FLEXIBLE", "Pantallas flexibles"], ["OTRO", "Otro tipo de pantalla"]] as const;
interface FormaPersonalizada { id: string; nombre: string; }

export function FormularioEspecificacion({ productos, formasPersonalizadas: formasIniciales, inicial, especificacionId }: { productos: ProductoTecnico[]; formasPersonalizadas: FormaPersonalizada[]; inicial?: Partial<Formulario>; especificacionId?: string }) {
  const [errorServidor, setErrorServidor] = useState("");
  const [mensajeExito, setMensajeExito] = useState("");
  const [formasPersonalizadas, setFormasPersonalizadas] = useState(formasIniciales);
  const [creandoForma, setCreandoForma] = useState(false);
  const [nuevaForma, setNuevaForma] = useState("");
  const [errorForma, setErrorForma] = useState("");
  const [analizandoImagen, setAnalizandoImagen] = useState(false);
  const [analisisCompleto, setAnalisisCompleto] = useState(false);
  const [advertenciasAnalisis, setAdvertenciasAnalisis] = useState<string[]>([]);
  const [analizandoFichaB, setAnalizandoFichaB] = useState(false);
  const [archivoDf, setArchivoDf] = useState<File | null>(null);
  const [archivoSes, setArchivoSes] = useState<File | null>(null);
  const [analisisFichaB, setAnalisisFichaB] = useState<{ datos: DatosFichaB; modeloOpenAI: string } | null>(null);
  const [rutaRegreso, setRutaRegreso] = useState("/paralelo/registros");
  const [datosFichaB, setDatosFichaB] = useState<DatosFichaB | null>(productos.find(p => p.id === (inicial?.productoId ?? productos[0]?.id))?.fichaB ?? null);
  const { register, handleSubmit, control, setValue, reset, formState: { errors, isSubmitting } } = useForm<Formulario>({ resolver: zodResolver(esquema), defaultValues: { productoId: productos[0]?.id ?? "", tipoFormaPantalla: "DOS_PUNTO_CINCO_D", tipoFormaOtro: "", cristalFrontal: "", refrescoHz: null, ...inicial } });
  const productoId = useWatch({ control, name: "productoId" }); const forma = useWatch({ control, name: "tipoFormaPantalla" });
  const producto = productos.find(p => p.id === productoId);
  useEffect(() => { const tarea = window.setTimeout(() => setRutaRegreso(obtenerRutaRetornoEdicion("/paralelo/registros")), 0); return () => window.clearTimeout(tarea); }, []);
  const campo = "w-full rounded-2xl border border-white/60 bg-white/65 px-4 py-3 font-mono outline-none focus:ring-2 focus:ring-purple-400/50";
  const cargarFicha = async (archivo?: File) => {
    if (!archivo) return;
    setErrorServidor("");
    setAnalisisCompleto(false);
    setAdvertenciasAnalisis([]);
    if (!productoId) { setErrorServidor("Selecciona primero el producto que vas a completar."); return; }
    if (archivo.size > 10 * 1024 * 1024) { setErrorServidor("La imagen no debe superar 10 MB."); return; }
    setAnalizandoImagen(true);
    try {
      const formData = new FormData();
      formData.set("productoId", productoId);
      formData.set("imagen", archivo);
      const { datos } = await analizarFichaTecnicaDesdeImagen(formData);
      const campos: (keyof Formulario)[] = ["tecnologia", "diagonalMm", "diagonalPulgadas", "anchoDisplayMm", "altoDisplayMm", "aspectRatio", "resolucionAnchoPx", "resolucionAltoPx", "densidadPpi", "profundidadColor", "areaDisplayPorcentaje", "cristalFrontal", "refrescoHz"];
      for (const nombre of campos) {
        const valor = datos[nombre as keyof typeof datos];
        if (valor !== null && valor !== undefined) setValue(nombre, valor as never, { shouldDirty: true, shouldValidate: true });
      }
      setValue("tipoFormaPantalla", datos.tipoFormaPantalla, { shouldDirty: true, shouldValidate: true });
      setAdvertenciasAnalisis(datos.advertencias);
      setAnalisisCompleto(true);
    } catch (causa) {
      setErrorServidor(causa instanceof globalThis.Error ? causa.message : "No fue posible analizar la ficha técnica.");
    } finally {
      setAnalizandoImagen(false);
    }
  };
  const agregarForma = async () => { setErrorForma(""); try { const creada = await crearFormaPantallaPersonalizada(nuevaForma); setFormasPersonalizadas((actuales) => actuales.some((formaActual) => formaActual.id === creada.id) ? actuales : [...actuales, creada].sort((a, b) => a.nombre.localeCompare(b.nombre, "es-MX"))); const valor = `PERSONALIZADA:${creada.nombre}`; setValue("tipoFormaPantalla", valor, { shouldValidate: true }); setValue("tipoFormaOtro", creada.nombre, { shouldValidate: true }); setNuevaForma(""); setCreandoForma(false); } catch (causa) { setErrorForma(causa instanceof globalThis.Error ? causa.message : "No fue posible crear el tipo de pantalla."); } };
  const cargarFichaB = async () => { if (!archivoDf || !archivoSes || !productoId) return; setErrorServidor(""); setAnalisisFichaB(null); setAnalizandoFichaB(true); try { const formData = new FormData(); formData.set("productoId", productoId); formData.set("df", archivoDf); formData.set("ses", archivoSes); const resultado = await analizarFichaBDesdeImagenes(formData); setAnalisisFichaB(resultado); setDatosFichaB(resultado.datos); } catch (causa) { setErrorServidor(causa instanceof globalThis.Error ? causa.message : "No fue posible analizar la ficha técnica B."); } finally { setAnalizandoFichaB(false); } };
  const enviar = async (datos: Formulario) => { setErrorServidor(""); setMensajeExito(""); try { const personalizada = datos.tipoFormaPantalla.startsWith("PERSONALIZADA:") ? datos.tipoFormaPantalla.slice("PERSONALIZADA:".length) : ""; const resultado = await guardarEspecificacion({ ...datos, tipoFormaPantalla: personalizada ? "OTRO" : datos.tipoFormaPantalla as "PLANA" | "CURVA" | "DOS_PUNTO_CINCO_D" | "TRES_D" | "FLEXIBLE" | "PLEGABLE" | "OTRO", tipoFormaOtro: personalizada || datos.tipoFormaOtro }, especificacionId); if (!resultado.guardado) throw new globalThis.Error("No fue posible comprobar el registro técnico."); if (datosFichaB) await guardarFichaBDesdeImagenes(datos.productoId, { datos: datosFichaB, modeloOpenAI: analisisFichaB?.modeloOpenAI }); setMensajeExito(especificacionId ? "Registro técnico actualizado correctamente" : "Fichas técnicas guardadas correctamente"); window.setTimeout(() => window.location.assign(especificacionId ? rutaRegreso : "/paralelo/registros"), 1200); } catch (causa) { setErrorServidor(causa instanceof globalThis.Error ? causa.message : "No fue posible guardar los parámetros."); } };
  return <form onSubmit={handleSubmit(enviar)} className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
    <div className="space-y-6">
      <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl sm:p-8"><h2 className="mb-2 text-2xl font-semibold">Identificación del producto</h2><p className="mb-6 text-sm text-[var(--on-surface-variant)]">Selecciona el producto para consultar, completar o actualizar sus fichas técnicas.</p><label><span className="mb-2 block font-mono text-xs uppercase tracking-wider">Producto</span>{especificacionId ? <><select disabled value={productoId} className={campo}><option value={productoId}>{producto?.clave} · {producto?.descripcion}</option></select><input type="hidden" {...register("productoId")} /></> : <select {...register("productoId", { onChange: (evento) => { const elegido = productos.find(p => p.id === String(evento.target.value)); reset({ productoId: elegido?.id ?? "", tipoFormaPantalla: "DOS_PUNTO_CINCO_D", tipoFormaOtro: "", cristalFrontal: "", refrescoHz: null, ...elegido?.fichaA }); setDatosFichaB(elegido?.fichaB ?? null); setArchivoDf(null); setArchivoSes(null); setAnalisisFichaB(null); } })} className={campo}><option value="">Selecciona un producto...</option>{productos.map(p => <option key={p.id} value={p.id}>{p.clave} · {p.descripcion}</option>)}</select>}</label>{producto && <div className="mt-5 grid gap-4 rounded-[2rem] bg-white/45 p-5 sm:grid-cols-[6rem_1fr]"><div className="relative grid aspect-square w-24 place-items-center overflow-hidden rounded-2xl bg-purple-100 text-3xl text-[var(--primary)]"><ImagenProducto url={producto.imagenUrl} descripcion={producto.descripcion} sizes="96px" icono="bx-image" /></div><div className="grid gap-3 sm:grid-cols-2"><Dato etiqueta="Clave" valor={producto.clave} /><Dato etiqueta="Modelo" valor={producto.modelo} /><Dato etiqueta="Línea" valor={producto.linea} /><Dato etiqueta="Marca" valor={producto.marca} /><Dato etiqueta="Tipo" valor={producto.tipo} /><div className="flex flex-wrap gap-2 sm:col-span-2"><EstadoFicha letra="A" existe={Boolean(producto.fichaA)} /><EstadoFicha letra="B" existe={Boolean(producto.fichaB)} /></div></div></div>}{errors.productoId && <Error texto={errors.productoId.message} />}</section>
      {!especificacionId && <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-[var(--primary)]">Ficha técnica A</p><h2 className="mt-1 text-2xl font-semibold">Cargar los datos técnicos de la ficha técnica A</h2><p className="mt-2 max-w-2xl text-[var(--on-surface-variant)]">Puedes llenar los campos manualmente o seleccionar una captura de la ficha técnica A. La imagen se analiza, pero nada se guarda hasta que revises los datos y pulses Guardar parámetros.</p></div><label className={`inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-3 font-semibold text-white ${analizandoImagen || !productoId ? "pointer-events-none opacity-60" : ""}`}><i className={`bx ${analizandoImagen ? "bx-loader-alt animate-spin" : "bx-image-add"}`} />{analizandoImagen ? "Analizando imagen..." : "Cargar ficha A por imagen"}<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" disabled={analizandoImagen || !productoId} onChange={(evento) => { const archivo = evento.target.files?.[0]; void cargarFicha(archivo); evento.target.value = ""; }} /></label></div>{analisisCompleto && <div role="status" className="mt-5 rounded-[2rem] border border-emerald-200 bg-emerald-50/80 p-5 text-emerald-900"><p className="font-semibold"><i className="bx bx-check-circle mr-2" />Datos de la ficha A extraídos. Revisa o modifica cada campo antes de guardar.</p>{advertenciasAnalisis.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{advertenciasAnalisis.map((advertencia) => <li key={advertencia}>{advertencia}</li>)}</ul>}</div>}</section>}
      <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl sm:p-8"><h2 className="mb-6 text-2xl font-semibold">Parámetros de pantalla · Ficha A</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <Campo etiqueta="Tipo / Tecnología" error={errors.tecnologia?.message}><input {...register("tecnologia")} placeholder="Ej. AMOLED" className={campo} /></Campo>
        <Campo etiqueta="Tipo o forma" error={errors.tipoFormaPantalla?.message}><select {...register("tipoFormaPantalla", { onChange: (evento) => { const valor = String(evento.target.value); if (valor.startsWith("PERSONALIZADA:")) setValue("tipoFormaOtro", valor.slice("PERSONALIZADA:".length)); } })} className={campo}>{formas.map(([v,n]) => <option key={v} value={v}>{n}</option>)}{formasPersonalizadas.length > 0 && <optgroup label="Tipos creados">{formasPersonalizadas.map((tipo) => <option key={tipo.id} value={`PERSONALIZADA:${tipo.nombre}`}>{tipo.nombre}</option>)}</optgroup>}</select><button type="button" onClick={() => setCreandoForma((actual) => !actual)} className="mt-2 inline-flex items-center gap-2 rounded-full px-3 py-2 text-sm font-semibold text-[var(--primary)] hover:bg-purple-100"><i className="bx bx-plus" />Crear otro tipo de pantalla</button>{creandoForma && <div className="mt-2 rounded-2xl bg-white/45 p-3"><input value={nuevaForma} onChange={(evento) => setNuevaForma(evento.target.value)} placeholder="Nombre del nuevo tipo" className={campo} />{errorForma && <Error texto={errorForma} />}<div className="mt-2 flex justify-end gap-2"><button type="button" onClick={() => { setCreandoForma(false); setErrorForma(""); }} className="rounded-full px-4 py-2 text-sm">Cancelar</button><button type="button" onClick={agregarForma} className="rounded-full bg-[var(--primary)] px-4 py-2 text-sm font-semibold text-white">Agregar a la lista</button></div></div>}</Campo>
        {forma === "OTRO" && <Campo etiqueta="Describe la forma" error={errors.tipoFormaOtro?.message}><input {...register("tipoFormaOtro")} className={campo} /></Campo>}
        <Campo etiqueta="Diagonal (mm)" error={errors.diagonalMm?.message}><input type="number" step="0.001" {...register("diagonalMm", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Diagonal (pulgadas)" error={errors.diagonalPulgadas?.message}><input type="number" step="0.001" {...register("diagonalPulgadas", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Ancho display (mm)" error={errors.anchoDisplayMm?.message}><input type="number" step="0.001" {...register("anchoDisplayMm", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Alto display (mm)" error={errors.altoDisplayMm?.message}><input type="number" step="0.001" {...register("altoDisplayMm", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Aspect ratio" error={errors.aspectRatio?.message}><input {...register("aspectRatio")} placeholder="Ej. 19.5:9" className={campo} /></Campo>
        <Campo etiqueta="Resolución (ancho px)" error={errors.resolucionAnchoPx?.message}><input type="number" {...register("resolucionAnchoPx", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Resolución (alto px)" error={errors.resolucionAltoPx?.message}><input type="number" {...register("resolucionAltoPx", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Densidad (ppi)" error={errors.densidadPpi?.message}><input type="number" {...register("densidadPpi", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Color depth" error={errors.profundidadColor?.message}><input {...register("profundidadColor")} placeholder="Ej. 24 bits" className={campo} /></Campo>
        <Campo etiqueta="Área de pantalla (%)" error={errors.areaDisplayPorcentaje?.message}><input type="number" min="0" max="100" step="0.01" {...register("areaDisplayPorcentaje", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Cristal frontal (opcional)" error={errors.cristalFrontal?.message}><input {...register("cristalFrontal")} placeholder="Ej. Gorilla Glass Victus" className={campo} /></Campo>
        <Campo etiqueta="Refresco (Hz, opcional)" error={errors.refrescoHz?.message}><input type="number" {...register("refrescoHz", { setValueAs: (valor) => valor === "" ? null : Number(valor) })} className={campo} /></Campo>
      </div></section>
      {!especificacionId && <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl sm:p-8"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-[var(--primary)]">Ficha técnica B</p><h2 className="mt-1 text-2xl font-semibold">Diseño físico y sensores</h2><p className="mt-2 text-[var(--on-surface-variant)]">Selecciona las dos capturas requeridas: DF para diseño físico y SES para sensores.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><SelectorFichaB etiqueta="Imagen DF" archivo={archivoDf} cambiar={(archivo) => { setArchivoDf(archivo); setAnalisisFichaB(null); }} /><SelectorFichaB etiqueta="Imagen SES" archivo={archivoSes} cambiar={(archivo) => { setArchivoSes(archivo); setAnalisisFichaB(null); }} /></div><button type="button" disabled={!productoId || !archivoDf || !archivoSes || analizandoFichaB} onClick={() => void cargarFichaB()} className="mt-5 inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-3 font-semibold text-white disabled:opacity-60"><i className={`bx ${analizandoFichaB ? "bx-loader-alt animate-spin" : "bx-images"}`} />{analizandoFichaB ? "Analizando DF y SES..." : "Cargar ficha B por imágenes"}</button>{analisisFichaB && <div role="status" className="mt-5 rounded-[2rem] border border-emerald-200 bg-emerald-50/80 p-5 text-emerald-900"><p className="font-semibold"><i className="bx bx-check-circle mr-2" />Ficha B extraída. Se guardará junto con los parámetros.</p>{analisisFichaB.datos.advertencias.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{analisisFichaB.datos.advertencias.map((advertencia) => <li key={advertencia}>{advertencia}</li>)}</ul>}</div>}<div className="mt-7 border-t border-white/60 pt-7"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-semibold">Datos técnicos de la ficha B</h3>{!datosFichaB && <button type="button" onClick={() => setDatosFichaB(fichaBVacia())} className="rounded-full bg-purple-100 px-5 py-3 font-semibold text-[var(--primary)]"><i className="bx bx-plus mr-2" />Agregar manualmente</button>}</div>{datosFichaB ? <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{camposFichaB.map(({ clave, etiqueta, tipo }) => <CampoB key={clave} etiqueta={etiqueta} tipo={tipo} valor={datosFichaB[clave]} cambiar={(valor) => setDatosFichaB(actual => actual ? { ...actual, [clave]: valor } : actual)} />)}<CampoB etiqueta="Sensores (separados por coma)" tipo="texto" valor={datosFichaB.sensores.join(", ")} cambiar={(valor) => setDatosFichaB(actual => actual ? { ...actual, sensores: String(valor ?? "").split(",").map(v => v.trim()).filter(Boolean) } : actual)} /></div> : <p className="mt-5 rounded-2xl bg-white/45 p-5 text-[var(--on-surface-variant)]">Este producto todavía no tiene ficha B. Puedes cargar las imágenes DF y SES o agregar los parámetros manualmente.</p>}</div></section>}
    </div>
    <aside><div className="sticky top-28 rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl"><h2 className="text-xl font-semibold">Ficha técnica</h2><p className="mt-2 text-[var(--on-surface-variant)]">Todos los parámetros son obligatorios para que Smart Match pueda comparar el producto.</p>{errorServidor && <p role="alert" className="mt-5 rounded-2xl bg-red-100 p-4 text-[var(--error)]">{errorServidor}</p>}{mensajeExito && <p role="status" className="mt-5 rounded-2xl bg-emerald-100 p-4 font-semibold text-emerald-800"><i className="bx bx-check-circle mr-2" />{mensajeExito}</p>}<button disabled={isSubmitting || !productos.length || Boolean(mensajeExito)} className="mt-6 w-full rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-4 font-bold text-white disabled:opacity-60">{isSubmitting ? "Guardando..." : especificacionId ? "Guardar cambios" : "Guardar parámetros"}</button></div></aside>
  </form>;
}
function Campo({ etiqueta, error, children }: { etiqueta: string; error?: string; children: React.ReactNode }) { return <label><span className="mb-2 block font-mono text-xs uppercase tracking-wider text-[var(--on-surface-variant)]">{etiqueta}</span>{children}{error && <Error texto={error} />}</label>; }
function Error({ texto }: { texto?: string }) { return texto ? <span className="mt-1 block text-sm text-[var(--error)]">{texto}</span> : null; }
function Dato({ etiqueta, valor }: { etiqueta: string; valor: string }) { return <div><span className="font-mono text-xs uppercase text-[var(--on-surface-variant)]">{etiqueta}</span><strong className="block">{valor}</strong></div>; }
function SelectorFichaB({ etiqueta, archivo, cambiar }: { etiqueta: string; archivo: File | null; cambiar: (archivo: File | null) => void }) { return <label className="cursor-pointer rounded-2xl border border-dashed border-[var(--outline-variant)] bg-white/45 p-4 focus-within:ring-2 focus-within:ring-purple-400/50"><span className="font-mono text-xs uppercase tracking-wider text-[var(--on-surface-variant)]">{etiqueta}</span><span className="mt-2 flex items-center gap-2 font-semibold text-[var(--primary)]"><i className="bx bx-image-add text-xl" />{archivo?.name ?? "Seleccionar imagen"}</span><input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={(evento) => cambiar(evento.target.files?.[0] ?? null)} /></label>; }
const camposFichaB: { clave: keyof DatosFichaB; etiqueta: string; tipo: "numero" | "texto" | "booleano" }[] = [{ clave: "anchoCuerpoMm", etiqueta: "Ancho del cuerpo (mm)", tipo: "numero" }, { clave: "altoCuerpoMm", etiqueta: "Alto del cuerpo (mm)", tipo: "numero" }, { clave: "grosorCuerpoMm", etiqueta: "Grosor (mm)", tipo: "numero" }, { clave: "anchoDisplayMm", etiqueta: "Ancho display (mm)", tipo: "numero" }, { clave: "altoDisplayMm", etiqueta: "Alto display (mm)", tipo: "numero" }, { clave: "diagonalDisplayMm", etiqueta: "Diagonal display (mm)", tipo: "numero" }, { clave: "aspectRatio", etiqueta: "Aspect ratio", tipo: "texto" }, { clave: "areaDisplayPorcentaje", etiqueta: "Área de pantalla (%)", tipo: "numero" }, { clave: "biselLateralMm", etiqueta: "Bisel lateral (mm)", tipo: "numero" }, { clave: "biselVerticalTotalMm", etiqueta: "Bisel vertical total (mm)", tipo: "numero" }, { clave: "curvatura", etiqueta: "Curvatura", tipo: "texto" }, { clave: "pesoGramos", etiqueta: "Peso (g)", tipo: "numero" }, { clave: "volumenCm3", etiqueta: "Volumen (cm³)", tipo: "numero" }, { clave: "materiales", etiqueta: "Materiales", tipo: "texto" }, { clave: "colores", etiqueta: "Colores", tipo: "texto" }, { clave: "certificaciones", etiqueta: "Certificaciones", tipo: "texto" }, { clave: "tipoHuella", etiqueta: "Tipo de huella", tipo: "texto" }, { clave: "huellaBajoPantalla", etiqueta: "Huella bajo pantalla", tipo: "booleano" }];
function fichaBVacia(): DatosFichaB { return { anchoCuerpoMm: null, altoCuerpoMm: null, grosorCuerpoMm: null, anchoDisplayMm: null, altoDisplayMm: null, diagonalDisplayMm: null, aspectRatio: null, areaDisplayPorcentaje: null, biselLateralMm: null, biselVerticalTotalMm: null, curvatura: null, pesoGramos: null, volumenCm3: null, materiales: null, colores: null, certificaciones: null, tipoHuella: null, huellaBajoPantalla: null, sensores: [], advertencias: [] }; }
function CampoB({ etiqueta, tipo, valor, cambiar }: { etiqueta: string; tipo: "numero" | "texto" | "booleano"; valor: unknown; cambiar: (valor: string | number | boolean | null) => void }) { const clase = "w-full rounded-2xl border border-white/60 bg-white/65 px-4 py-3 font-mono outline-none focus:ring-2 focus:ring-purple-400/50"; return <label><span className="mb-2 block font-mono text-xs uppercase tracking-wider text-[var(--on-surface-variant)]">{etiqueta}</span>{tipo === "booleano" ? <select value={valor === null ? "" : valor ? "si" : "no"} onChange={e => cambiar(e.target.value === "" ? null : e.target.value === "si")} className={clase}><option value="">Sin determinar</option><option value="si">Sí</option><option value="no">No</option></select> : <input type={tipo === "numero" ? "number" : "text"} step={tipo === "numero" ? "0.001" : undefined} value={valor === null || valor === undefined ? "" : String(valor)} onChange={e => cambiar(tipo === "numero" ? (e.target.value === "" ? null : Number(e.target.value)) : (e.target.value || null))} className={clase} />}</label>; }
function EstadoFicha({ letra, existe }: { letra: string; existe: boolean }) { return <span className={`rounded-full px-3 py-1 text-xs font-semibold ${existe ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-900"}`}><i className={`bx ${existe ? "bx-check-circle" : "bx-time-five"} mr-1`} />Ficha {letra}: {existe ? "registrada" : "pendiente"}</span>; }
