"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import Image from "next/image";
import { useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { z } from "zod";
import { crearFormaPantallaPersonalizada, guardarEspecificacion } from "@/actions/especificaciones";

export interface ProductoTecnico { id: string; clave: string; descripcion: string; modelo: string; imagenUrl: string | null; linea: string; marca: string; tipo: string; }
const esquema = z.object({ productoId: z.string().min(1, "Selecciona un producto"), tecnologia: z.string().trim().min(1, "Escribe la tecnología"), tipoFormaPantalla: z.string().min(1, "Selecciona una forma"), tipoFormaOtro: z.string(), diagonalMm: z.number().positive("Debe ser mayor que cero"), diagonalPulgadas: z.number().positive("Debe ser mayor que cero"), anchoDisplayMm: z.number().positive("Debe ser mayor que cero"), altoDisplayMm: z.number().positive("Debe ser mayor que cero"), aspectRatio: z.string().trim().min(1, "Escribe el aspect ratio"), resolucionAnchoPx: z.number().int().positive("Resolución inválida"), resolucionAltoPx: z.number().int().positive("Resolución inválida"), densidadPpi: z.number().int().positive("Densidad inválida"), profundidadColor: z.string().trim().min(1, "Escribe la profundidad de color"), areaDisplayPorcentaje: z.number().min(0).max(100, "El área debe estar entre 0 y 100"), cristalFrontal: z.string(), refrescoHz: z.number().int().positive("Frecuencia inválida").nullable() }).refine(d => d.tipoFormaPantalla !== "OTRO" || d.tipoFormaOtro.trim(), { path: ["tipoFormaOtro"], message: "Describe la forma" });
type Formulario = z.infer<typeof esquema>;
const formas = [["PLANA", "Pantallas planas (Cristal 2D)"], ["DOS_PUNTO_CINCO_D", "Cristal 2.5D (Pantalla plana con borde biselado)"], ["CURVA", "Pantallas curvas (3D o Dual-Edge)"], ["TRES_D", "Evoluciones extremas: Waterfall y 4D (Quad-Curved)"], ["PLEGABLE", "Pantallas plegables (Foldables)"], ["FLEXIBLE", "Pantallas flexibles"], ["OTRO", "Otro tipo de pantalla"]] as const;
interface FormaPersonalizada { id: string; nombre: string; }

export function FormularioEspecificacion({ productos, formasPersonalizadas: formasIniciales, inicial, especificacionId }: { productos: ProductoTecnico[]; formasPersonalizadas: FormaPersonalizada[]; inicial?: Partial<Formulario>; especificacionId?: string }) {
  const [errorServidor, setErrorServidor] = useState("");
  const [mensajeExito, setMensajeExito] = useState("");
  const [formasPersonalizadas, setFormasPersonalizadas] = useState(formasIniciales);
  const [creandoForma, setCreandoForma] = useState(false);
  const [nuevaForma, setNuevaForma] = useState("");
  const [errorForma, setErrorForma] = useState("");
  const { register, handleSubmit, control, setValue, formState: { errors, isSubmitting } } = useForm<Formulario>({ resolver: zodResolver(esquema), defaultValues: { productoId: productos[0]?.id ?? "", tipoFormaPantalla: "PLANA", tipoFormaOtro: "", cristalFrontal: "", refrescoHz: null, ...inicial } });
  const productoId = useWatch({ control, name: "productoId" }); const forma = useWatch({ control, name: "tipoFormaPantalla" });
  const producto = productos.find(p => p.id === productoId);
  const campo = "w-full rounded-2xl border border-white/60 bg-white/65 px-4 py-3 font-mono outline-none focus:ring-2 focus:ring-purple-400/50";
  const agregarForma = async () => { setErrorForma(""); try { const creada = await crearFormaPantallaPersonalizada(nuevaForma); setFormasPersonalizadas((actuales) => actuales.some((formaActual) => formaActual.id === creada.id) ? actuales : [...actuales, creada].sort((a, b) => a.nombre.localeCompare(b.nombre, "es-MX"))); const valor = `PERSONALIZADA:${creada.nombre}`; setValue("tipoFormaPantalla", valor, { shouldValidate: true }); setValue("tipoFormaOtro", creada.nombre, { shouldValidate: true }); setNuevaForma(""); setCreandoForma(false); } catch (causa) { setErrorForma(causa instanceof globalThis.Error ? causa.message : "No fue posible crear el tipo de pantalla."); } };
  const enviar = async (datos: Formulario) => { setErrorServidor(""); setMensajeExito(""); try { const personalizada = datos.tipoFormaPantalla.startsWith("PERSONALIZADA:") ? datos.tipoFormaPantalla.slice("PERSONALIZADA:".length) : ""; const resultado = await guardarEspecificacion({ ...datos, tipoFormaPantalla: personalizada ? "OTRO" : datos.tipoFormaPantalla as "PLANA" | "CURVA" | "DOS_PUNTO_CINCO_D" | "TRES_D" | "FLEXIBLE" | "PLEGABLE" | "OTRO", tipoFormaOtro: personalizada || datos.tipoFormaOtro }, especificacionId); if (!resultado.guardado) throw new globalThis.Error("No fue posible comprobar el registro técnico."); setMensajeExito(especificacionId ? "Registro técnico actualizado correctamente" : "Registro técnico guardado correctamente"); window.setTimeout(() => window.location.assign("/paralelo/registros"), 1200); } catch (causa) { setErrorServidor(causa instanceof globalThis.Error ? causa.message : "No fue posible guardar los parámetros."); } };
  return <form onSubmit={handleSubmit(enviar)} className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
    <div className="space-y-6">
      <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl sm:p-8"><h2 className="mb-6 text-2xl font-semibold">Identificación del producto</h2><label><span className="mb-2 block font-mono text-xs uppercase tracking-wider">Producto</span>{especificacionId ? <><select disabled value={productoId} className={campo}><option value={productoId}>{producto?.clave} · {producto?.descripcion}</option></select><input type="hidden" {...register("productoId")} /></> : <select {...register("productoId")} className={campo}><option value="">Selecciona un producto...</option>{productos.map(p => <option key={p.id} value={p.id}>{p.clave} · {p.descripcion}</option>)}</select>}</label>{producto && <div className="mt-5 grid gap-4 rounded-[2rem] bg-white/45 p-5 sm:grid-cols-[6rem_1fr]"><div className="relative grid aspect-square w-24 place-items-center overflow-hidden rounded-2xl bg-purple-100 text-3xl text-[var(--primary)]">{producto.imagenUrl ? <Image unoptimized fill sizes="96px" src={producto.imagenUrl} alt={`Imagen de ${producto.descripcion}`} className="object-contain" /> : <i className="bx bx-image" />}</div><div className="grid gap-3 sm:grid-cols-2"><Dato etiqueta="Clave" valor={producto.clave} /><Dato etiqueta="Modelo" valor={producto.modelo} /><Dato etiqueta="Línea" valor={producto.linea} /><Dato etiqueta="Marca" valor={producto.marca} /><Dato etiqueta="Tipo" valor={producto.tipo} /></div></div>}{errors.productoId && <Error texto={errors.productoId.message} />}</section>
      <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl sm:p-8"><h2 className="mb-6 text-2xl font-semibold">Parámetros de pantalla</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <Campo etiqueta="Tipo / Tecnología" error={errors.tecnologia?.message}><input {...register("tecnologia")} placeholder="Ej. AMOLED" className={campo} /></Campo>
        <Campo etiqueta="Tipo o forma" error={errors.tipoFormaPantalla?.message}><select {...register("tipoFormaPantalla", { onChange: (evento) => { const valor = String(evento.target.value); if (valor.startsWith("PERSONALIZADA:")) setValue("tipoFormaOtro", valor.slice("PERSONALIZADA:".length)); } })} className={campo}>{formas.map(([v,n]) => <option key={v} value={v}>{n}</option>)}{formasPersonalizadas.length > 0 && <optgroup label="Tipos creados">{formasPersonalizadas.map((tipo) => <option key={tipo.id} value={`PERSONALIZADA:${tipo.nombre}`}>{tipo.nombre}</option>)}</optgroup>}</select><button type="button" onClick={() => setCreandoForma((actual) => !actual)} className="mt-2 inline-flex items-center gap-2 rounded-full px-3 py-2 text-sm font-semibold text-[var(--primary)] hover:bg-purple-100"><i className="bx bx-plus" />Crear otro tipo de pantalla</button>{creandoForma && <div className="mt-2 rounded-2xl bg-white/45 p-3"><input value={nuevaForma} onChange={(evento) => setNuevaForma(evento.target.value)} placeholder="Nombre del nuevo tipo" className={campo} />{errorForma && <Error texto={errorForma} />}<div className="mt-2 flex justify-end gap-2"><button type="button" onClick={() => { setCreandoForma(false); setErrorForma(""); }} className="rounded-full px-4 py-2 text-sm">Cancelar</button><button type="button" onClick={agregarForma} className="rounded-full bg-[var(--primary)] px-4 py-2 text-sm font-semibold text-white">Agregar a la lista</button></div></div>}</Campo>
        {forma === "OTRO" && <Campo etiqueta="Describe la forma" error={errors.tipoFormaOtro?.message}><input {...register("tipoFormaOtro")} className={campo} /></Campo>}
        <Campo etiqueta="Diagonal (mm)" error={errors.diagonalMm?.message}><input type="number" step="0.001" {...register("diagonalMm", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Diagonal (pulgadas)" error={errors.diagonalPulgadas?.message}><input type="number" step="0.001" {...register("diagonalPulgadas", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Ancho display (mm)" error={errors.anchoDisplayMm?.message}><input type="number" step="0.001" {...register("anchoDisplayMm", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Alto display (mm)" error={errors.altoDisplayMm?.message}><input type="number" step="0.001" {...register("altoDisplayMm", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Aspect ratio" error={errors.aspectRatio?.message}><input {...register("aspectRatio")} placeholder="Ej. 19.5:9" className={campo} /></Campo>
        <Campo etiqueta="Resolución (ancho px)" error={errors.resolucionAnchoPx?.message}><input type="number" {...register("resolucionAnchoPx", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Resolución (alto px)" error={errors.resolucionAltoPx?.message}><input type="number" {...register("resolucionAltoPx", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Densidad (ppi)" error={errors.densidadPpi?.message}><input type="number" {...register("densidadPpi", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Color depth" error={errors.profundidadColor?.message}><input {...register("profundidadColor")} placeholder="Ej. 24 bits" className={campo} /></Campo>
        <Campo etiqueta="Área de pantalla (%)" error={errors.areaDisplayPorcentaje?.message}><input type="number" min="0" max="100" step="0.01" {...register("areaDisplayPorcentaje", { valueAsNumber: true })} className={campo} /></Campo>
        <Campo etiqueta="Cristal frontal (opcional)" error={errors.cristalFrontal?.message}><input {...register("cristalFrontal")} placeholder="Ej. Gorilla Glass Victus" className={campo} /></Campo>
        <Campo etiqueta="Refresco (Hz, opcional)" error={errors.refrescoHz?.message}><input type="number" {...register("refrescoHz", { setValueAs: (valor) => valor === "" ? null : Number(valor) })} className={campo} /></Campo>
      </div></section>
    </div>
    <aside><div className="sticky top-28 rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl"><h2 className="text-xl font-semibold">Ficha técnica</h2><p className="mt-2 text-[var(--on-surface-variant)]">Todos los parámetros son obligatorios para que Smart Match pueda comparar el producto.</p>{errorServidor && <p role="alert" className="mt-5 rounded-2xl bg-red-100 p-4 text-[var(--error)]">{errorServidor}</p>}{mensajeExito && <p role="status" className="mt-5 rounded-2xl bg-emerald-100 p-4 font-semibold text-emerald-800"><i className="bx bx-check-circle mr-2" />{mensajeExito}</p>}<button disabled={isSubmitting || !productos.length || Boolean(mensajeExito)} className="mt-6 w-full rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-4 font-bold text-white disabled:opacity-60">{isSubmitting ? "Guardando..." : especificacionId ? "Guardar cambios" : "Guardar parámetros"}</button></div></aside>
  </form>;
}
function Campo({ etiqueta, error, children }: { etiqueta: string; error?: string; children: React.ReactNode }) { return <label><span className="mb-2 block font-mono text-xs uppercase tracking-wider text-[var(--on-surface-variant)]">{etiqueta}</span>{children}{error && <Error texto={error} />}</label>; }
function Error({ texto }: { texto?: string }) { return texto ? <span className="mt-1 block text-sm text-[var(--error)]">{texto}</span> : null; }
function Dato({ etiqueta, valor }: { etiqueta: string; valor: string }) { return <div><span className="font-mono text-xs uppercase text-[var(--on-surface-variant)]">{etiqueta}</span><strong className="block">{valor}</strong></div>; }
