"use client";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { eliminarEspecificacion } from "@/actions/especificaciones";

export interface RegistroTecnico { id: string; clave: string; descripcion: string; imagenUrl: string | null; }
export function ListadoRegistros({ registros }: { registros: RegistroTecnico[] }) {
  const router = useRouter(); const [aEliminar, setAEliminar] = useState<RegistroTecnico | null>(null); const [error, setError] = useState(""); const [eliminando, setEliminando] = useState(false);
  const eliminar = async () => { if (!aEliminar) return; setEliminando(true); setError(""); try { await eliminarEspecificacion(aEliminar.id); setAEliminar(null); router.refresh(); } catch (causa) { setError(causa instanceof Error ? causa.message : "No fue posible eliminar."); } finally { setEliminando(false); } };
  if (!registros.length) return <div className="rounded-[2.5rem] border border-white/60 bg-white/40 p-10 text-center"><i className="bx bx-layer text-5xl text-[var(--primary)]" /><h2 className="mt-3 text-2xl font-semibold">Sin registros técnicos</h2><p className="mt-2 text-[var(--on-surface-variant)]">Registra los parámetros del primer producto.</p></div>;
  return <><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{registros.map(r => <article key={r.id} className="rounded-[2.5rem] border border-white/60 bg-white/40 p-5 shadow-[0_20px_50px_rgba(0,0,0,0.05)] backdrop-blur-xl"><div className="relative grid aspect-[16/9] place-items-center overflow-hidden rounded-[2rem] bg-gradient-to-br from-purple-100 to-pink-100 text-5xl text-[var(--primary)]">{r.imagenUrl ? <Image unoptimized fill sizes="(min-width: 1280px) 30vw, (min-width: 640px) 50vw, 100vw" src={r.imagenUrl} alt={`Imagen de ${r.descripcion}`} className="object-cover" /> : <i className="bx bx-mobile-alt" />}</div><p className="mt-5 font-mono text-sm font-semibold text-[var(--primary)]">{r.clave}</p><h2 className="mt-1 min-h-14 text-xl font-semibold">{r.descripcion}</h2><div className="mt-5 grid grid-cols-2 gap-3"><Link href={`/paralelo/${r.id}/editar`} className="inline-flex items-center justify-center gap-2 rounded-full bg-purple-100 px-4 py-3 font-semibold text-[var(--primary)]"><i className="bx bx-edit-alt" />Editar</Link><button onClick={() => setAEliminar(r)} aria-label={`Eliminar registro ${r.clave}`} className="inline-flex items-center justify-center gap-2 rounded-full bg-red-100 px-4 py-3 font-semibold text-[var(--error)]"><i className="bx bx-trash" />Eliminar</button></div></article>)}</div>{aEliminar && <div className="fixed inset-0 z-[100] grid place-items-center bg-[var(--on-surface)]/30 p-4 backdrop-blur-md"><section role="alertdialog" aria-modal="true" className="w-full max-w-lg rounded-[2.5rem] bg-[var(--surface)] p-8 shadow-2xl"><h2 className="text-2xl font-bold">Eliminar parámetros</h2><p className="mt-3">Se eliminará la ficha técnica de <strong>{aEliminar.clave}</strong>, no el producto.</p>{error && <p role="alert" className="mt-4 rounded-2xl bg-red-100 p-4 text-[var(--error)]">{error}</p>}<div className="mt-7 flex justify-end gap-3"><button disabled={eliminando} onClick={() => setAEliminar(null)} className="rounded-full border px-5 py-3">Cancelar</button><button disabled={eliminando} onClick={eliminar} className="rounded-full bg-[var(--error)] px-5 py-3 font-semibold text-white">Eliminar</button></div></section></div>}</>;
}
