import { ErrorConsulta, PaginaCuenta, PaginacionCuenta } from "@/components/mercadolibre/pagina-cuenta";
import { formarFechaMercadoLibre, obtenerCuentaMercadoLibre, paginaSegura } from "@/lib/mercadolibre/consultas";
import { obtenerEnvios, traducirEstadoMercadoLibre, traducirLogisticaMercadoLibre } from "@/lib/mercadolibre/datos";
export const dynamic = "force-dynamic";

export default async function Envios({ searchParams }: { searchParams: Promise<{ pagina?: string }> }) {
  const cuenta = await obtenerCuentaMercadoLibre(); const pagina = paginaSegura((await searchParams).pagina); let contenido: React.ReactNode = null;
  let resultado: Awaited<ReturnType<typeof obtenerEnvios>> | null = null; let mensajeError: string | null = null;
  if (cuenta) try { resultado = await obtenerEnvios(cuenta, pagina); } catch (error) { mensajeError = error instanceof Error ? error.message : "Error inesperado."; }
  if (mensajeError) contenido = <ErrorConsulta mensaje={mensajeError} />;
  else if (resultado) contenido = <><div className="grid w-full gap-4 sm:grid-cols-2 xl:grid-cols-3">{resultado.datos.map(envio => <article key={envio.id} className="rounded-[2rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs text-[var(--primary)]">ENVÍO {envio.id}</p><h2 className="mt-1 text-xl font-semibold">{traducirEstadoMercadoLibre(envio.status)}</h2><p className="mt-1 text-sm text-[var(--on-surface-variant)]">{traducirEstadoMercadoLibre(envio.substatus)}</p></div><i className="bx bx-package text-3xl text-[var(--primary)]" /></div><dl className="mt-4 space-y-2 text-sm text-[var(--on-surface-variant)]"><div><dt className="font-semibold">Última actualización</dt><dd>{formarFechaMercadoLibre(envio.last_updated)}</dd></div><div><dt className="font-semibold">Número de seguimiento</dt><dd>{envio.tracking_number ?? "No informado"}</dd></div><div><dt className="font-semibold">Método de seguimiento</dt><dd>{envio.tracking_method ?? "No informado"}</dd></div><div><dt className="font-semibold">Tipo de logística</dt><dd>{traducirLogisticaMercadoLibre(envio.logistic?.type)}</dd></div><div><dt className="font-semibold">Dirección logística</dt><dd>{traducirLogisticaMercadoLibre(envio.logistic?.direction)}</dd></div><div><dt className="font-semibold">Destino</dt><dd>{[envio.receiver_address?.city?.name, envio.receiver_address?.state?.name].filter(Boolean).join(", ") || "No informado"}</dd></div></dl></article>)}{!resultado.datos.length && <p className="rounded-[2rem] bg-white/40 p-8 text-center sm:col-span-2 xl:col-span-3">Las compras de esta página no tienen envíos disponibles.</p>}</div><PaginacionCuenta pagina={pagina} total={resultado.totalOrdenes} ruta="/cuenta/envios" /></>;
  return <PaginaCuenta cuenta={cuenta} titulo="Envíos" descripcion="Información logística asociada a las compras de la cuenta. La paginación sigue las compras más recientes.">{contenido}</PaginaCuenta>;
}
