"use client";

import { useState } from "react";
import { analizarLoteFichasABC, importarLoteFichasABCConIA, validarManifiestoFichasABCSeguro as validarLoteFichasAB, validarManifiestoFichasABCSeguro as validarLoteFichasABC } from "@/actions/importacion-fichas-abc";

type Validacion = Awaited<ReturnType<typeof validarLoteFichasAB>>["resultados"];
type Analisis = Awaited<ReturnType<typeof analizarLoteFichasABC>>["resultados"];

export function ImportadorFichasABC() {
  const [paso, setPaso] = useState(1), [loteId, setLoteId] = useState(""), [mensaje, setMensaje] = useState(""), [ocupado, setOcupado] = useState(false);
  const [validacion, setValidacion] = useState<Validacion>([]), [analisis, setAnalisis] = useState<Analisis>([]);
  const validar = async (formData: FormData) => { setOcupado(true); setMensaje("Validando plantilla e imágenes..."); try { const r = await validarLoteFichasABC(formData); setValidacion(r.resultados); if (r.valido) { setLoteId(r.loteId); setPaso(2); setMensaje(`${r.resultados.length} registros listos. La ficha C es opcional.`); } else setMensaje("Corrige los errores indicados y vuelve a cargar los archivos."); } catch (e) { setMensaje(e instanceof Error ? e.message : "No fue posible validar el lote."); } finally { setOcupado(false); } };
  const analizar = async () => { setOcupado(true); try { let r = await analizarLoteFichasABC(loteId); while (!r.completo) { setMensaje(`${r.analizados} de ${r.total} productos analizados...`); r = await analizarLoteFichasABC(loteId); } setAnalisis(r.resultados); setPaso(3); setMensaje("Análisis terminado. Revisa el resumen antes de importar."); } catch (e) { setMensaje(e instanceof Error ? e.message : "El análisis se interrumpió; puedes continuarlo."); } finally { setOcupado(false); } };
  const importar = async () => { setOcupado(true); setMensaje("Analizando imágenes con IA e importando las fichas..."); try { const r = await importarLoteFichasABCConIA(loteId); setPaso(4); setMensaje(`${r.importados} fichas A y B analizadas e importadas correctamente.`); } catch (e) { setMensaje(e instanceof Error ? e.message : "No fue posible analizar e importar el lote."); } finally { setOcupado(false); } };
  const reiniciar = () => { setPaso(1); setLoteId(""); setValidacion([]); setAnalisis([]); setMensaje(""); };
  return <div className="space-y-6"><ol className="grid gap-3 sm:grid-cols-4">{["Cargar y validar", "Preparar datos", "Revisar", "Importar"].map((t, i) => <li key={t} className={`rounded-3xl border p-4 ${paso === i + 1 ? "border-purple-300 bg-purple-100/70" : paso > i + 1 ? "border-emerald-200 bg-emerald-50/70" : "border-white/60 bg-white/40"}`}><span className="font-mono text-xs">PASO {i + 1}</span><strong className="mt-1 block">{t}</strong></li>)}</ol>
    {paso === 1 && <form action={validar} className="rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-semibold">Selecciona la plantilla y las imágenes</h2><p className="mt-2 max-w-3xl text-[var(--on-surface-variant)]">A, DF y SES son obligatorias. La Ruta C puede quedar vacía y no bloquea el lote.</p></div><a href="/plantillas/plantilla-fichas-tecnicas-abc.xlsx" download className="inline-flex items-center gap-2 rounded-full bg-purple-100 px-5 py-3 font-semibold text-[var(--primary)]"><i className="bx bx-download" />Descargar plantilla</a></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Archivo nombre="excel" etiqueta="Plantilla A, B y C (.xlsx)" aceptar=".xlsx" /><Archivo nombre="imagenes" etiqueta="Imágenes A, DF, SES y C opcional (.zip)" aceptar=".zip,application/zip" /></div><button disabled={ocupado} className="mt-6 rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-3 font-semibold text-white disabled:opacity-60">{ocupado ? "Validando..." : "Validar archivos"}</button></form>}
    {mensaje && <p role="status" className="rounded-3xl border border-white/60 bg-white/60 p-5 font-medium">{mensaje}</p>}{validacion.length > 0 && paso <= 2 && <TablaValidacion filas={validacion} />}
    {paso === 2 && <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-8"><h2 className="text-2xl font-semibold">Archivos validados sin consumir créditos</h2><p className="mt-2 text-[var(--on-surface-variant)]">La vista previa sólo confirma Claves, rutas e imágenes. OpenAI se utilizará hasta la confirmación final, junto con la importación.</p><div className="mt-6 flex gap-3"><button disabled={ocupado} onClick={analizar} className="rounded-full bg-[var(--primary)] px-6 py-3 font-semibold text-white disabled:opacity-60">{ocupado ? "Preparando..." : "Preparar vista previa"}</button><button disabled={ocupado} onClick={reiniciar} className="rounded-full border px-6 py-3">Cambiar archivos</button></div></section>}
    {paso === 3 && <><TablaRevision filas={analisis} /><div className="flex justify-end gap-3"><button disabled={ocupado} onClick={reiniciar} className="rounded-full border px-6 py-3">Cancelar lote</button><button disabled={ocupado} onClick={importar} className="rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-3 font-semibold text-white disabled:opacity-60">{ocupado ? "Importando..." : "Confirmar importación"}</button></div></>}
    {paso === 4 && <section className="rounded-[2.5rem] border border-emerald-200 bg-emerald-50/80 p-8"><i className="bx bx-check-circle text-5xl text-emerald-700" /><h2 className="mt-3 text-2xl font-semibold">Importación terminada</h2><p className="mt-2">Las fichas A y B fueron actualizadas. La ficha C permaneció opcional.</p><button onClick={reiniciar} className="mt-5 rounded-full bg-emerald-700 px-6 py-3 font-semibold text-white">Importar otro lote</button></section>}
  </div>;
}
function Archivo({ nombre, etiqueta, aceptar }: { nombre: string; etiqueta: string; aceptar: string }) { return <label className="rounded-3xl border border-dashed border-purple-300 bg-white/50 p-6"><span className="block font-semibold">{etiqueta}</span><input required type="file" name={nombre} accept={aceptar} className="mt-4 block w-full text-sm file:mr-3 file:rounded-full file:border-0 file:bg-purple-100 file:px-4 file:py-2 file:font-semibold file:text-[var(--primary)]" /></label>; }
function TablaValidacion({ filas }: { filas: Validacion }) { return <section className="overflow-x-auto rounded-[2rem] bg-white/50 p-4"><table className="w-full min-w-[55rem] text-left text-sm"><thead><tr>{["Fila", "Clave", "Modelo", "Ficha A", "DF", "SES", "Ficha C", "Estado"].map(t => <th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{filas.map(f => <tr key={`${f.numero}-${f.clave}`} className="border-t"><td className="p-3">{f.numero}</td><td className="p-3 font-mono">{f.clave}</td><td className="p-3">{f.modelo}</td><td className="p-3">{f.aEncontrada ? "Lista" : "Falta"}</td><td className="p-3">{f.dfEncontrada ? "Lista" : "Falta"}</td><td className="p-3">{f.sesEncontrada ? "Lista" : "Falta"}</td><td className="p-3">{f.cIncluida ? "Incluida" : "Opcional"}</td><td className="p-3">{f.problema || "Listo"}</td></tr>)}</tbody></table></section>; }
function TablaRevision({ filas }: { filas: Analisis }) { return <section className="overflow-x-auto rounded-[2rem] bg-white/50 p-4"><h2 className="p-3 text-2xl font-semibold">Revisión del lote</h2><table className="w-full min-w-[65rem] text-left text-sm"><thead><tr>{["Clave", "Modelo", "Ficha A", "Ficha B · Diseño", "Ficha B · Sensores", "Ficha C", "Advertencias"].map(t => <th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{filas.map(r => <tr key={r.fila.clave} className="border-t align-top"><td className="p-3 font-mono">{r.fila.clave}</td><td className="p-3">{r.fila.modelo}</td><td className="p-3">{r.fichaA.tecnologia ?? "—"} · {r.fichaA.anchoDisplayMm ?? "—"} × {r.fichaA.altoDisplayMm ?? "—"} mm</td><td className="p-3">{r.fichaB.anchoCuerpoMm ?? "—"} × {r.fichaB.altoCuerpoMm ?? "—"} mm</td><td className="p-3">{r.fichaB.sensores.join(", ") || "—"}</td><td className="p-3">{r.fila.rutaC ? "Incluida, pendiente de procesamiento" : "No incluida (opcional)"}</td><td className="max-w-72 p-3">{[...r.fichaA.advertencias, ...r.fichaB.advertencias].join("; ") || "Sin advertencias"}</td></tr>)}</tbody></table></section>; }
