"use client";

import { useState } from "react";
import { analizarLoteFichasB, importarLoteFichasB, validarLoteFichasB, type ResultadoAnalisisFichaB, type ResultadoValidacionFichaB } from "@/actions/fichas-b";

export function MigradorFichasB({ claveInicial }: { marcas: string[]; claveInicial: string }) {
  const [paso, setPaso] = useState(1), [loteId, setLoteId] = useState(""), [validaciones, setValidaciones] = useState<ResultadoValidacionFichaB[]>([]), [resultados, setResultados] = useState<ResultadoAnalisisFichaB[]>([]), [ocupado, setOcupado] = useState(false), [mensaje, setMensaje] = useState("");
  const validar = async (formData: FormData) => { setOcupado(true); setMensaje(""); try { const r = await validarLoteFichasB(formData); setValidaciones(r.resultados); setLoteId(r.loteId); if (r.listos) { setPaso(2); setMensaje(`${r.listos} de ${r.total} productos están listos para analizar.`); } else setMensaje("Ningún producto está listo. Corrige los errores indicados."); } catch (e) { setMensaje(e instanceof Error ? e.message : "No fue posible validar."); } finally { setOcupado(false); } };
  const analizar = async () => { setOcupado(true); setMensaje("Analizando imágenes DF y SES con OpenAI..."); try { let r = await analizarLoteFichasB(loteId); setResultados(r.resultados); while (!r.completo) { setMensaje(`${r.analizados} de ${r.total} fichas analizadas...`); r = await analizarLoteFichasB(loteId); setResultados(r.resultados); } setPaso(3); setMensaje(`${r.total} fichas analizadas. Revisa y corrige antes de importar.`); } catch (e) { setMensaje(e instanceof Error ? e.message : "El análisis se interrumpió. Puedes continuarlo sin perder el avance."); } finally { setOcupado(false); } };
  const importar = async () => { setOcupado(true); setMensaje("Guardando fichas B..."); try { const r = await importarLoteFichasB(loteId, resultados.map(x => ({ clave: x.fila.clave, datos: x.datos }))); setPaso(4); setMensaje(`${r.importados} fichas B fueron importadas correctamente.`); } catch (e) { setMensaje(e instanceof Error ? e.message : "No fue posible importar las fichas."); } finally { setOcupado(false); } };
  const reiniciar = () => { setPaso(1); setLoteId(""); setValidaciones([]); setResultados([]); setMensaje(""); };
  const actualizar = (clave: string, campo: keyof ResultadoAnalisisFichaB["datos"], valor: unknown) => setResultados(actuales => actuales.map(r => r.fila.clave === clave ? { ...r, datos: { ...r.datos, [campo]: valor } } : r));
  return <div className="space-y-6"><Pasos actual={paso} />
    {paso === 1 && <form action={validar} className="rounded-[2.5rem] border border-white/60 bg-white/40 p-6 backdrop-blur-xl sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold">Selecciona los archivos del lote</h2>{claveInicial && <p className="mt-1 text-sm">Clave seleccionada: <span className="font-mono">{claveInicial}</span></p>}</div><a href="/plantillas/plantilla-migracion-fichas-b.xlsx" download className="rounded-full bg-purple-100 px-5 py-3 font-semibold text-[var(--primary)]"><i className="bx bx-download mr-2" />Descargar plantilla</a></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Archivo nombre="excel" etiqueta="Plantilla de fichas B (.xlsx)" aceptar=".xlsx" /><Archivo nombre="imagenes" etiqueta="Imágenes DF y SES (.zip)" aceptar=".zip,application/zip" /></div><button disabled={ocupado} className="mt-6 rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-3 font-semibold text-white disabled:opacity-60">{ocupado ? "Validando..." : "Validar archivos"}</button></form>}
    {mensaje && <p role="status" className="rounded-3xl border border-white/60 bg-white/60 p-5 font-medium">{mensaje}</p>}
    {paso === 1 && validaciones.length > 0 && <TablaValidacion resultados={validaciones} />}
    {paso === 2 && <section className="rounded-[2.5rem] border border-white/60 bg-white/40 p-8"><h2 className="text-2xl font-semibold">Archivos listos</h2><p className="mt-2 text-[var(--on-surface-variant)]">El siguiente paso analiza las dos imágenes de cada producto y consume créditos de OpenAI.</p><div className="mt-6 flex gap-3"><button onClick={analizar} disabled={ocupado} className="rounded-full bg-[var(--primary)] px-6 py-3 font-semibold text-white disabled:opacity-60">{ocupado ? "Analizando..." : resultados.length ? "Continuar análisis" : "Analizar fichas B"}</button><button onClick={reiniciar} disabled={ocupado} className="rounded-full border px-6 py-3">Cambiar archivos</button></div></section>}
    {paso === 3 && <><VistaPrevia resultados={resultados} actualizar={actualizar} /><div className="flex justify-end gap-3"><button onClick={reiniciar} disabled={ocupado} className="rounded-full border px-6 py-3">Cancelar lote</button><button onClick={importar} disabled={ocupado} className="rounded-full bg-gradient-to-r from-[var(--primary)] to-[var(--primary-container)] px-6 py-3 font-semibold text-white disabled:opacity-60">{ocupado ? "Importando..." : "Confirmar importación"}</button></div></>}
    {paso === 4 && <section className="rounded-[2.5rem] border border-emerald-200 bg-emerald-50/80 p-8"><i className="bx bx-check-circle text-5xl text-emerald-700" /><h2 className="mt-3 text-2xl font-semibold">Importación terminada</h2><button onClick={reiniciar} className="mt-5 rounded-full bg-emerald-700 px-6 py-3 font-semibold text-white">Importar otro lote</button></section>}
  </div>;
}

function Pasos({ actual }: { actual: number }) { return <ol className="grid gap-3 sm:grid-cols-4">{["Cargar y validar", "Analizar fichas", "Revisar", "Importar"].map((t, i) => <li key={t} className={`rounded-3xl border p-4 ${actual === i + 1 ? "border-purple-300 bg-purple-100/70" : actual > i + 1 ? "border-emerald-200 bg-emerald-50/70" : "border-white/60 bg-white/40"}`}><span className="font-mono text-xs">PASO {i + 1}</span><strong className="mt-1 block">{t}</strong></li>)}</ol>; }
function Archivo({ nombre, etiqueta, aceptar }: { nombre: string; etiqueta: string; aceptar: string }) { return <label className="rounded-3xl border border-dashed border-purple-300 bg-white/50 p-6"><span className="block font-semibold">{etiqueta}</span><input required type="file" name={nombre} accept={aceptar} className="mt-4 block w-full text-sm file:mr-3 file:rounded-full file:border-0 file:bg-purple-100 file:px-4 file:py-2 file:font-semibold file:text-[var(--primary)]" /></label>; }
function TablaValidacion({ resultados }: { resultados: ResultadoValidacionFichaB[] }) { return <section className="overflow-x-auto rounded-[2rem] bg-white/50 p-4"><table className="w-full min-w-[55rem] text-left text-sm"><thead><tr>{["Fila", "Clave", "Modelo", "DF", "SES", "Estado"].map(t => <th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{resultados.map(r => <tr key={`${r.fila}-${r.clave}`} className="border-t"><td className="p-3">{r.fila}</td><td className="p-3 font-mono">{r.clave}</td><td className="p-3">{r.modelo}</td><td className="p-3">{r.dfEncontrado ? "Encontrado" : "Falta"}</td><td className="p-3">{r.sesEncontrado ? "Encontrado" : "Falta"}</td><td className="p-3"><span className={r.estado === "Listo" ? "text-emerald-700" : "text-red-700"}>{r.problema || "Listo"}</span></td></tr>)}</tbody></table></section>; }

const camposNumero = [["anchoCuerpoMm", "Ancho cuerpo (mm)"], ["altoCuerpoMm", "Alto cuerpo (mm)"], ["grosorCuerpoMm", "Grosor (mm)"], ["pesoGramos", "Peso (g)"], ["volumenCm3", "Volumen (cm³)"]] as const;
const camposTexto = [["curvatura", "Curvatura"], ["materiales", "Materiales"], ["colores", "Colores"], ["certificaciones", "Certificaciones"], ["tipoHuella", "Tipo de huella"]] as const;
function VistaPrevia({ resultados, actualizar }: { resultados: ResultadoAnalisisFichaB[]; actualizar: (clave: string, campo: keyof ResultadoAnalisisFichaB["datos"], valor: unknown) => void }) { return <section className="space-y-4"><div><h2 className="text-2xl font-semibold">Vista previa editable</h2><p className="mt-1 text-sm text-[var(--on-surface-variant)]">Las medidas del display, diagonal, proporción y área se tomarán automáticamente de la Ficha A. Los biseles se calculan al confirmar.</p></div>{resultados.map(r => <article key={r.fila.clave} className="rounded-[2rem] border border-white/60 bg-white/50 p-5"><h3 className="text-xl font-semibold"><span className="font-mono text-[var(--primary)]">{r.fila.clave}</span> · {r.fila.modelo}</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{camposNumero.map(([c, e]) => <Campo key={c} etiqueta={e}><input type="number" step="any" value={r.datos[c] ?? ""} onChange={x => actualizar(r.fila.clave, c, x.target.value === "" ? null : Number(x.target.value))} className="w-full rounded-xl bg-white/80 px-3 py-2" /></Campo>)}{camposTexto.map(([c, e]) => <Campo key={c} etiqueta={e}><input value={r.datos[c] ?? ""} onChange={x => actualizar(r.fila.clave, c, x.target.value || null)} className="w-full rounded-xl bg-white/80 px-3 py-2" /></Campo>)}<Campo etiqueta="Huella bajo pantalla"><select value={r.datos.huellaBajoPantalla === null ? "" : String(r.datos.huellaBajoPantalla)} onChange={x => actualizar(r.fila.clave, "huellaBajoPantalla", x.target.value === "" ? null : x.target.value === "true")} className="w-full rounded-xl bg-white/80 px-3 py-2"><option value="">No determinado</option><option value="true">Sí</option><option value="false">No</option></select></Campo><Campo etiqueta="Sensores (uno por línea)"><textarea value={r.datos.sensores.join("\n")} onChange={x => actualizar(r.fila.clave, "sensores", x.target.value.split("\n").map(v => v.trim()).filter(Boolean))} className="min-h-24 w-full rounded-xl bg-white/80 px-3 py-2" /></Campo><Campo etiqueta="Advertencias"><textarea value={r.datos.advertencias.join("\n")} onChange={x => actualizar(r.fila.clave, "advertencias", x.target.value.split("\n").map(v => v.trim()).filter(Boolean))} className="min-h-24 w-full rounded-xl bg-white/80 px-3 py-2" /></Campo></div></article>)}</section>; }
function Campo({ etiqueta, children }: { etiqueta: string; children: React.ReactNode }) { return <label className="grid gap-1 text-sm font-semibold"><span>{etiqueta}</span>{children}</label>; }
