"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { editarProductosMasivamente } from "@/actions/productos";

type Opcion = { id: string; nombre: string; detalle?: string };
type ProductoSeleccionable = { id: string; clave: string; descripcion: string };
const POR_PAGINA = 10;
const operaciones = [["AGREGAR_UBICACION", "Agregar ubicación"], ["QUITAR_UBICACION", "Quitar ubicación"], ["REEMPLAZAR_UBICACION", "Reemplazar ubicación"], ["CAMBIAR_LINEA", "Cambiar línea"], ["CAMBIAR_MARCA", "Cambiar marca"], ["CAMBIAR_TIPO", "Cambiar tipo de producto"]] as const;

export function EdicionMasiva({ productos, ubicaciones, lineas, marcas, tipos }: { productos: ProductoSeleccionable[]; ubicaciones: Opcion[]; lineas: Opcion[]; marcas: Opcion[]; tipos: Opcion[] }) {
  const router = useRouter(); const [abierto, setAbierto] = useState(false); const [pagina, setPagina] = useState(1); const [seleccionados, setSeleccionados] = useState<string[]>([]); const [operacion, setOperacion] = useState<(typeof operaciones)[number][0]>("AGREGAR_UBICACION"); const [valorId, setValorId] = useState(""); const [reemplazoId, setReemplazoId] = useState(""); const [confirmando, setConfirmando] = useState(false); const [resultado, setResultado] = useState(""); const [mensaje, setMensaje] = useState(""); const [pendiente, iniciar] = useTransition();
  const paginas = Math.max(1, Math.ceil(productos.length / POR_PAGINA)); const visibles = productos.slice((pagina - 1) * POR_PAGINA, pagina * POR_PAGINA); const idsVisibles = visibles.map(p => p.id); const paginaCompleta = idsVisibles.length > 0 && idsVisibles.every(id => seleccionados.includes(id));
  const opciones = operacion === "CAMBIAR_LINEA" ? lineas : operacion === "CAMBIAR_MARCA" ? marcas : operacion === "CAMBIAR_TIPO" ? tipos : ubicaciones;
  const alternar = (id: string) => setSeleccionados(actual => actual.includes(id) ? actual.filter(item => item !== id) : [...actual, id]);
  const alternarPagina = () => setSeleccionados(actual => paginaCompleta ? actual.filter(id => !idsVisibles.includes(id)) : [...new Set([...actual, ...idsVisibles])]);
  const reiniciar = () => { setSeleccionados([]); setValorId(""); setReemplazoId(""); setConfirmando(false); setResultado(""); setMensaje(""); };
  const aplicar = () => iniciar(async () => { try { const datos = await editarProductosMasivamente({ productoIds: seleccionados, operacion, valorId, reemplazoId: operacion === "REEMPLAZAR_UBICACION" ? reemplazoId : undefined }); if (datos.error) { setMensaje(datos.error); setConfirmando(false); return; } setResultado(`${datos.modificados} productos se editaron correctamente${datos.omitidos ? ` y ${datos.omitidos} fueron omitidos para conservar datos válidos` : ""}.`); setConfirmando(false); router.refresh(); } catch { setMensaje("No fue posible aplicar los cambios. Revisa las selecciones e inténtalo nuevamente."); } });
  return <div><button type="button" onClick={() => setAbierto(true)} className="inline-flex items-center justify-center gap-2 rounded-full bg-purple-100 px-5 py-3 font-semibold text-[var(--primary)]"><i className="bx bx-edit" />Edición masiva</button>{abierto && <div className="fixed inset-0 z-[100] grid place-items-center bg-[var(--on-surface)]/30 p-4 backdrop-blur-md"><section role="dialog" aria-modal="true" aria-labelledby="titulo-edicion-masiva" className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-[2.5rem] bg-[var(--surface)] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><h2 id="titulo-edicion-masiva" className="text-2xl font-bold">Edición masiva</h2><p className="mt-1 text-sm text-[var(--on-surface-variant)]">Selecciona productos de cualquier página. La selección se conserva mientras navegas.</p></div><button type="button" onClick={() => setAbierto(false)} className="grid size-10 place-items-center rounded-full bg-white/70" aria-label="Cerrar"><i className="bx bx-x text-2xl" /></button></div>
      {resultado ? <div className="mt-8 rounded-[2rem] bg-emerald-50 p-6 text-center text-emerald-900"><i className="bx bx-check-circle text-5xl" /><h3 className="mt-3 text-xl font-bold">Edición masiva completada</h3><p className="mt-2">{resultado}</p><p className="mt-2 font-semibold">¿Quieres seguir editando masivamente?</p><div className="mt-5 flex flex-col-reverse justify-center gap-3 sm:flex-row"><button type="button" onClick={() => setAbierto(false)} className="rounded-full border border-emerald-300 px-5 py-3 font-semibold">Finalizar</button><button type="button" onClick={reiniciar} className="rounded-full bg-[var(--primary)] px-5 py-3 font-semibold text-white">Sí, seguir editando</button></div></div> : <>
      <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div><strong>{seleccionados.length} seleccionados</strong><span className="ml-3 text-sm text-[var(--on-surface-variant)]">Página {pagina} de {paginas}</span></div><button type="button" onClick={alternarPagina} className="rounded-full bg-white/70 px-4 py-2 text-sm font-semibold">{paginaCompleta ? "Quitar selección de esta página" : "Seleccionar esta página"}</button></div>
      <div className="mt-3 grid min-h-52 content-start gap-2 sm:grid-cols-2">{visibles.map(producto => <label key={producto.id} className="flex cursor-pointer items-center gap-3 rounded-2xl bg-white/55 p-3"><input type="checkbox" checked={seleccionados.includes(producto.id)} onChange={() => alternar(producto.id)} className="size-4 accent-[var(--primary)]" /><span className="min-w-0"><strong className="block truncate">{producto.clave}</strong><span className="block truncate text-xs text-[var(--on-surface-variant)]">{producto.descripcion}</span></span></label>)}</div>
      <nav aria-label="Páginas de productos para edición masiva" className="mt-3 flex items-center justify-center gap-3"><button type="button" disabled={pagina === 1} onClick={() => setPagina(actual => actual - 1)} className="grid size-9 place-items-center rounded-full bg-white/70 disabled:opacity-35"><i className="bx bx-chevron-left" /></button><span className="font-mono text-sm">{pagina} / {paginas}</span><button type="button" disabled={pagina === paginas} onClick={() => setPagina(actual => actual + 1)} className="grid size-9 place-items-center rounded-full bg-white/70 disabled:opacity-35"><i className="bx bx-chevron-right" /></button></nav>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Operación<select value={operacion} onChange={evento => { setOperacion(evento.target.value as typeof operacion); setValorId(""); setReemplazoId(""); setConfirmando(false); }} className="mt-2 w-full rounded-2xl bg-white/70 px-4 py-3">{operaciones.map(([valor, nombre]) => <option key={valor} value={valor}>{nombre}</option>)}</select></label><label className="text-sm font-semibold">{operacion === "REEMPLAZAR_UBICACION" ? "Ubicación actual" : "Valor a aplicar"}<select value={valorId} onChange={evento => { setValorId(evento.target.value); setConfirmando(false); }} className="mt-2 w-full rounded-2xl bg-white/70 px-4 py-3"><option value="">Seleccionar…</option>{opciones.map(opcion => <option key={opcion.id} value={opcion.id}>{opcion.nombre}{opcion.detalle ? ` · ${opcion.detalle}` : ""}</option>)}</select></label>{operacion === "REEMPLAZAR_UBICACION" && <label className="text-sm font-semibold sm:col-start-2">Nueva ubicación<select value={reemplazoId} onChange={evento => { setReemplazoId(evento.target.value); setConfirmando(false); }} className="mt-2 w-full rounded-2xl bg-white/70 px-4 py-3"><option value="">Seleccionar…</option>{ubicaciones.filter(opcion => opcion.id !== valorId).map(opcion => <option key={opcion.id} value={opcion.id}>{opcion.nombre} · {opcion.detalle}</option>)}</select></label>}</div>
      {mensaje && <p role="alert" className="mt-4 rounded-2xl bg-red-100 p-4 text-sm text-[var(--error)]">{mensaje}</p>}{confirmando && <div className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-950"><strong>Confirma los cambios:</strong> se aplicará “{operaciones.find(([valor]) => valor === operacion)?.[1]}” a {seleccionados.length} productos seleccionados en {paginas} páginas disponibles.</div>}
      <div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={() => setAbierto(false)} className="rounded-full border px-5 py-3 font-semibold">Cancelar</button>{confirmando ? <button type="button" disabled={pendiente} onClick={aplicar} className="rounded-full bg-[var(--primary)] px-5 py-3 font-semibold text-white disabled:opacity-60">{pendiente ? "Aplicando…" : `Confirmar edición de ${seleccionados.length}`}</button> : <button type="button" disabled={!seleccionados.length || !valorId || (operacion === "REEMPLAZAR_UBICACION" && (!reemplazoId || reemplazoId === valorId))} onClick={() => setConfirmando(true)} className="rounded-full bg-[var(--primary)] px-5 py-3 font-semibold text-white disabled:opacity-40">Revisar cambios</button>}</div></>}
    </section></div>}</div>;
}
