"use client";

import Link from "next/link";
import { useState } from "react";
import { eliminarProducto } from "@/actions/productos";
import { ImagenProducto } from "@/components/productos/imagen-producto";
import { datosMarketplace } from "@/lib/marketplaces";
import type { ProductoInventario } from "@/types/producto";

const estado = (n: number) => n <= 20 ? "bg-red-500" : n <= 400 ? "bg-amber-500" : "bg-emerald-500";
const titulos = ["Imagen", "Clave", "Descripción", "Línea", "Existencia", "Modelo", "Marca", "Cuenta asociada / Marketplace", "Color", "Clave MLFull", "Código universal", "Acciones"];

export function TablaInventario({ productos }: { productos: ProductoInventario[] }) {
  const [eliminados, setEliminados] = useState<string[]>([]); const [productoAEliminar, setProductoAEliminar] = useState<ProductoInventario | null>(null); const [pasoConfirmacion, setPasoConfirmacion] = useState<1 | 2>(1); const visibles = productos.filter(producto => !eliminados.includes(producto.id));
  const cerrar = () => { setProductoAEliminar(null); setPasoConfirmacion(1); };
  const eliminar = async () => { if (!productoAEliminar) return; await eliminarProducto(productoAEliminar.id); setEliminados(actual => [...actual, productoAEliminar.id]); cerrar(); };
  if (!visibles.length) return <div className="grid min-h-72 place-items-center p-8 text-center"><div><i className="bx bx-search-alt text-5xl text-[var(--outline)]" /><h2 className="mt-3 text-xl font-semibold">No encontramos productos</h2><p className="text-[var(--on-surface-variant)]">Prueba con otros filtros.</p></div></div>;
  return <><div className="overflow-x-auto"><table className="w-full min-w-[1560px] text-left"><thead className="bg-[var(--surface-container-high)]/90 font-mono text-xs uppercase tracking-wider text-[var(--on-surface-variant)]"><tr>{titulos.map(titulo => <th key={titulo} className="px-4 py-4 font-medium">{titulo}</th>)}</tr></thead><tbody>{visibles.map(producto => <tr key={producto.id} className="border-t border-white/50 hover:bg-white/35">
    <td className="px-4 py-3"><div className="relative grid size-12 place-items-center overflow-hidden rounded-2xl bg-gradient-to-br from-purple-100 to-pink-100 text-2xl text-[var(--primary)]"><ImagenProducto url={producto.imagenUrl} descripcion={producto.descripcion} sizes="48px" icono={producto.tipoProducto === "Teléfono" ? "bx-mobile-alt" : "bx-shape-square"} /></div></td>
    <td className="px-4 py-3 font-mono text-sm font-semibold text-[var(--primary)]">{producto.clave}</td><td className="max-w-56 px-4 py-3 font-semibold">{producto.descripcion}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-200/50 px-3 py-1 text-sm">{producto.linea}</span></td><td className="px-4 py-3"><span className="inline-flex items-center gap-2 font-semibold"><span className={`size-2 rounded-full ${estado(producto.existencia)}`} />{producto.existencia.toLocaleString("es-MX")}</span></td><td className="px-4 py-3">{producto.modelo}</td><td className="px-4 py-3">{producto.marca}</td>
    <td className="min-w-60 px-4 py-3 text-left">{producto.ubicaciones.length ? <div className="space-y-1.5">{producto.ubicaciones.map((ubicacion, indice) => <div key={`${ubicacion.almacen}-${ubicacion.cuentaAsociada}-${indice}`} className="grid grid-cols-[minmax(0,1fr)_3.5rem] items-center text-left text-sm" title={`${ubicacion.cuentaAsociada} / ${datosMarketplace(ubicacion.marketplace).nombre}`}><span className="truncate pr-2">{ubicacion.cuentaAsociada}</span><span className="border-l border-[var(--outline-variant)] pl-2 font-mono font-bold text-[var(--primary)]">/ {datosMarketplace(ubicacion.marketplace).abreviatura}</span></div>)}</div> : <span className="text-[var(--on-surface-variant)]">—</span>}</td>
    <td className="px-4 py-3">{producto.color}</td><td className="px-4 py-3 font-mono text-sm">{producto.claveMLFull}</td><td className="px-4 py-3 font-mono text-sm">{producto.codigoUniversal}</td><td className="px-4 py-3"><div className="flex gap-2"><Link href={`/productos/${producto.id}/editar`} aria-label={`Editar ${producto.clave}`} title="Editar producto" className="grid size-11 place-items-center rounded-full bg-purple-100 text-xl text-[var(--primary)] hover:bg-purple-200"><i className="bx bx-edit-alt" /></Link><button type="button" onClick={() => { setProductoAEliminar(producto); setPasoConfirmacion(1); }} aria-label={`Eliminar ${producto.clave}`} title="Eliminar producto" className="grid size-11 place-items-center rounded-full bg-red-100 text-xl text-[var(--error)] hover:bg-red-200"><i className="bx bx-trash" /></button></div></td>
  </tr>)}</tbody></table></div>
  {productoAEliminar && <div className="fixed inset-0 z-[100] grid place-items-center bg-[var(--on-surface)]/30 p-4 backdrop-blur-md" onMouseDown={evento => { if (evento.target === evento.currentTarget) cerrar(); }}><section role="alertdialog" aria-modal="true" aria-labelledby="titulo-eliminar" className="w-full max-w-lg rounded-[2.5rem] border border-white/60 bg-[var(--surface)] p-7 shadow-2xl sm:p-9"><span className="grid size-14 place-items-center rounded-full bg-red-100 text-3xl text-[var(--error)]"><i className="bx bx-trash" /></span><h2 id="titulo-eliminar" className="mt-5 text-2xl font-bold">{pasoConfirmacion === 1 ? "¿Eliminar este producto?" : "Confirmación final"}</h2><p className="mt-3 text-[var(--on-surface-variant)]">{pasoConfirmacion === 1 ? <>Se eliminará <strong>{productoAEliminar.clave}</strong>. Esta acción afectará el inventario.</> : <>Confirma nuevamente que deseas eliminar definitivamente <strong>{productoAEliminar.clave}</strong>.</>}</p><div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={cerrar} className="rounded-full border border-[var(--outline-variant)] bg-white/60 px-5 py-3 font-semibold">Cancelar</button>{pasoConfirmacion === 1 ? <button type="button" onClick={() => setPasoConfirmacion(2)} className="rounded-full bg-red-100 px-5 py-3 font-semibold text-[var(--error)]">Continuar</button> : <button type="button" onClick={eliminar} className="rounded-full bg-[var(--error)] px-5 py-3 font-semibold text-white">Sí, eliminar definitivamente</button>}</div></section></div>}</>;
}
